"use strict";

/**
 * Tests for src/core/nnc/nominalization/nominalization.js
 */

const { createSuite } = require("./runner");

function run(ctx) {
    const s = createSuite("nnc_nominalization");

    s.eq(
        "Lessons 35-39 nominalization boundary API is exported",
        [
            typeof ctx.buildNominalizationBoundaryMetadata,
            typeof ctx.classifyNominalizationBoundaryCandidate,
            typeof ctx.classifyNominalizationFalsePositive,
            typeof ctx.getNominalizationBoundaryAntiConflationRules,
            typeof ctx.buildLesson35PreteritAgentivePursuitFrame,
            typeof ctx.getLesson35PreteritAgentiveSubsectionInventory,
            typeof ctx.buildLesson36NominalizedVncPursuitFrame,
            typeof ctx.getLesson36NominalizedVncSubsectionInventory,
            typeof ctx.buildLesson37DeverbalNounstemPursuitFrame,
            typeof ctx.getLesson37DeverbalNounstemSubsectionInventory,
            typeof ctx.buildLesson38ImpersonalPatientivePursuitFrame,
            typeof ctx.getLesson38ImpersonalPatientiveSubsectionInventory,
            typeof ctx.buildLesson39PatientiveOperationsPursuitFrame,
            typeof ctx.getLesson39PatientiveOperationsSubsectionInventory,
        ],
        ["function", "function", "function", "function", "function", "function", "function", "function", "function", "function", "function", "function", "function", "function"]
    );

    const boundary = ctx.buildNominalizationBoundaryMetadata();
    s.eq(
        "nominalization boundary is explicit, partial, and non-generative",
        {
            kind: boundary.kind,
            lessons: boundary.lessons,
            status: boundary.status,
            grammarAuthority: boundary.grammarAuthority,
            orthographyAuthority: boundary.orthographyAuthority,
            targetAuthority: boundary.targetAuthority,
            generationAllowed: boundary.generationAllowed,
            confirmedExamples: boundary.confirmedExamples,
            boundaries: boundary.boundaries,
            questionFields: boundary.structuralQuestions.map((question) => question.field),
        },
        {
            kind: "nominalization-boundary",
            lessons: [35, 36, 37, 38, 39],
            status: "partial",
            grammarAuthority: "Andrews PDF Lessons 35-39",
            orthographyAuthority: "Modern Nawat/Pipil orthography and confirmed Nawat forms",
            targetAuthority: "Andrews grammar rules with Nawat/Pipil orthographic realization",
            generationAllowed: false,
            confirmedExamples: [],
            boundaries: {
                hasGeneratedNominalSurfaces: true,
                hasGeneratedSLisActionNominalSurfaces: true,
                hasNominalizationProfile: true,
                hasPatientiveFamilyProfile: true,
                hasOwnerhoodGeneration: false,
                hasDeverbalLizZGeneration: false,
                hasFullPatientiveFamilyGeneration: false,
                hasStaticNominalizedVncData: false,
                changesGeneratedSurfaces: false,
                changesOrdinaryNncGeneration: false,
                changesVncGeneration: false,
            },
            questionFields: [
                "nominalizationKind",
                "sourceVnc",
                "stemUse",
                "semanticRole",
                "evidenceSource",
            ],
        }
    );

    s.eq(
        "generated patientivo surface remains unconfirmed full patientive evidence",
        ctx.classifyNominalizationBoundaryCandidate({
            candidate: "tamachti",
            nominalizationKind: "patientive-family",
            sourceVnc: "-(mati)",
            semanticRole: "patient/result",
            hasNominalizationProfile: true,
            hasPatientiveFamilyProfile: true,
            falsePositiveSource: "patientive-family-profile",
        }),
        {
            kind: "nominalization-boundary-candidate-classification",
            version: 1,
            candidate: "tamachti",
            nominalizationKind: "patientive-family",
            sourceVnc: "-(mati)",
            stemUse: "",
            semanticRole: "patient/result",
            evidenceSource: "",
            falsePositiveSource: "patientive-family-profile",
            hasNominalizationProfile: true,
            hasPatientiveFamilyProfile: true,
            confirmed: false,
            generationAllowed: false,
            diagnostics: [
                "nominalization-needs-nawat-evidence",
                "nominalization-category-recognized",
                "nominalization-profile-is-metadata-only",
                "patientive-family-profile-is-partial",
                "nominalization-false-positive-source",
            ],
            boundary,
        }
    );
    s.eq(
        "nominalization classifiers expose the LCM grammar frame contract",
        (() => {
            const classification = ctx.classifyNominalizationBoundaryCandidate({
                candidate: "tamachti",
                nominalizationKind: "patientive-family",
                sourceVnc: "-(mati)",
                hasNominalizationProfile: true,
                falsePositiveSource: "patientive-family-profile",
            });
            return {
                hasFrame: Boolean(classification.grammarFrame),
                unitKind: classification.frames.unitFrame.unitKind,
                routeStage: classification.frames.routeContract.routeStage,
                generationAllowed: classification.frames.routeContract.generationAllowed,
                stemKind: classification.frames.stemFrame.stemKind,
                diagnosticId: classification.contractDiagnostics[0].id,
                enumerableGrammarFrame: Object.prototype.propertyIsEnumerable.call(classification, "grammarFrame"),
            };
        })(),
        {
            hasFrame: true,
            unitKind: "nominalization",
            routeStage: "classify-boundary",
            generationAllowed: false,
            stemKind: "nominalization-source-candidate",
            diagnosticId: "nominalization-needs-nawat-evidence",
            enumerableGrammarFrame: false,
        }
    );

    s.eq(
        "ownerhood category is recognized but requires Nawat/Pipil evidence",
        ctx.classifyNominalizationBoundaryCandidate({
            candidate: "ownerhood candidate",
            nominalizationKind: "ownerhood",
            stemUse: "general-use",
            semanticRole: "owner",
        }).diagnostics,
        [
            "nominalization-needs-nawat-evidence",
            "nominalization-category-recognized",
            "nominalization-profile-absent",
            "patientive-family-profile-absent",
            "nominalization-unconfirmed",
        ]
    );

    s.eq(
        "Andrews examples remain structural false positives for Nawat forms",
        ctx.classifyNominalizationFalsePositive("andrews-example"),
        {
            kind: "nominalization-false-positive",
            version: 1,
            source: "andrews-example",
            isNominalizationEvidence: false,
            isOwnerhoodEvidence: false,
            isDeverbalLizZEvidence: false,
            isFullPatientiveFamilyEvidence: false,
            generationAllowed: false,
            diagnostics: ["nominalization-false-positive-source"],
            antiConflationRules: ctx.getNominalizationBoundaryAntiConflationRules(),
        }
    );

    s.ok(
        "nominalization anti-conflation rules reject generated-surface completion claims",
        ctx.getNominalizationBoundaryAntiConflationRules()
            .some((rule) => rule.includes("not complete Lessons 35-39 coverage"))
    );

    const lesson35Frame = ctx.buildLesson35PreteritAgentivePursuitFrame();
    s.eq(
        "Lesson 35 pursuit frame covers every Andrews preterit-agentive subsection",
        {
            kind: lesson35Frame.kind,
            stepNumber: lesson35Frame.stepNumber,
            aimStatus: lesson35Frame.aimStatus,
            pdfRefs: lesson35Frame.pdfRefs,
            subsectionRefs: lesson35Frame.subsectionInventory.map((entry) => entry.andrewsSection),
            generationAllowed: lesson35Frame.generationAllowed,
            closestPass: lesson35Frame.closestPass,
            hitCount: lesson35Frame.hitCount,
            missCount: lesson35Frame.missCount,
        },
        {
            kind: "lesson-35-preterit-agentive-pursuit-frame",
            stepNumber: 35,
            aimStatus: "shooting",
            pdfRefs: [
                "Andrews Lesson 35.1",
                "Andrews Lesson 35.2",
                "Andrews Lesson 35.3",
                "Andrews Lesson 35.4",
                "Andrews Lesson 35.5",
                "Andrews Lesson 35.6",
                "Andrews Lesson 35.7",
                "Andrews Lesson 35.8",
                "Andrews Lesson 35.9",
                "Andrews Lesson 35.10",
                "Andrews Lesson 35.11",
                "Andrews Lesson 35.12",
            ],
            subsectionRefs: [
                "35.1",
                "35.2",
                "35.3",
                "35.4",
                "35.5",
                "35.6",
                "35.7",
                "35.8",
                "35.9",
                "35.10",
                "35.11",
                "35.12",
            ],
            generationAllowed: false,
            closestPass: false,
            hitCount: 1,
            missCount: 0,
        }
    );
    s.eq(
        "Lesson 35 frame records preterit-agentive architecture and current boundaries",
        {
            process: lesson35Frame.overviewFrame.process,
            lessonKind: lesson35Frame.overviewFrame.lesson35Kind,
            restrictedPreteritFinal: lesson35Frame.absolutiveFrame.preteritTenseMorphAlwaysFinalInRestrictedStem,
            numberAlternation: lesson35Frame.numberPositionFrame.quiAndZeroCanAlternate,
            generalUseFormation: lesson35Frame.generalUseFrame.formation,
            possessiveSingular: lesson35Frame.possessiveStateFrame.singularSubjectNumberDyad,
            compoundAffective: lesson35Frame.compoundEmbedFrame.compoundAffectiveNncsSupportedStructurally,
            oldPersonBoundary: lesson35Frame.oldPersonFrame.distinguishesSimpleNounstemFromPreteritAgentiveStem,
            ownerhoodMatrices: lesson35Frame.ownerhoodFrame.ownerhoodMatrices,
            abundantMatrix: lesson35Frame.abundantOwnerhoodFrame.matrix,
            adverbialFocus: lesson35Frame.vncEmbedAdverbialFrame.adverbialModificationCanFocusSubjectOrObject,
            vncEmbedRouteFrames: lesson35Frame.vncEmbedAdverbialFrame.routeFrames.map((frame) => ({
                kind: frame.kind,
                sourcePrincipal: frame.sourcePrincipalVnc.formulaType,
                sourceAdjunct: frame.sourceAdjunctNnc.formulaType,
                embedRole: frame.embedRole,
                consumedObjectSlot: frame.consumedObjectSlot,
                valenceDelta: frame.valenceDelta,
                finalFormulaShape: frame.finalFormulaShape,
                finalFormulaShapeDoesNotLicenseRole: frame.finalFormulaShapeDoesNotLicenseRole,
                functionUseOwnsObjectSlots: frame.objectSlotOwnership.functionUseOwnsObjectSlots,
                sourceRouteFrameRequired: frame.sourceRouteFrameRequired,
                andrewsSection: frame.andrewsSection,
                generationStatus: frame.generationStatus,
            })),
            participantEmbedRoles: [
                lesson35Frame.frames.participantFrame.incorporatedObjectRouteFrame.embedRole,
                lesson35Frame.frames.participantFrame.incorporatedAdverbRouteFrame.embedRole,
            ],
            routeStage: lesson35Frame.frames.routeContract.routeStage,
            diagnosticId: lesson35Frame.contractDiagnostics[0].id,
        },
        {
            process: "VNC takes on NNC characteristics",
            lessonKind: "preterit-agentive-nnc",
            restrictedPreteritFinal: true,
            numberAlternation: true,
            generalUseFormation: "restricted preterit predicate embed plus (ca)-tl matrix",
            possessiveSingular: "uh-0",
            compoundAffective: true,
            oldPersonBoundary: true,
            ownerhoodMatrices: ["*tla-(-e)", "*tla-(-hua)"],
            abundantMatrix: "*tla-(-yo-a)",
            adverbialFocus: true,
            vncEmbedRouteFrames: [
                {
                    kind: "lesson-35-preterit-agentive-incorporation-route-frame",
                    sourcePrincipal: "CNV",
                    sourceAdjunct: "CNN",
                    embedRole: "incorporated-object",
                    consumedObjectSlot: "obj1",
                    valenceDelta: {
                        incorporatedObjectSlots: 1,
                        adverbialFunctionSlots: 0,
                        remainingExternalObjectSlots: 0,
                    },
                    finalFormulaShape: "preterit-agentive-nounstem-incorporated-in-vnc-matrix",
                    finalFormulaShapeDoesNotLicenseRole: true,
                    functionUseOwnsObjectSlots: false,
                    sourceRouteFrameRequired: true,
                    andrewsSection: "Andrews 35.12",
                    generationStatus: "diagnostic-only-nawat-evidence-required",
                },
                {
                    kind: "lesson-35-preterit-agentive-incorporation-route-frame",
                    sourcePrincipal: "CNV",
                    sourceAdjunct: "CNN",
                    embedRole: "incorporated-adverb",
                    consumedObjectSlot: "",
                    valenceDelta: {
                        incorporatedObjectSlots: 0,
                        adverbialFunctionSlots: 1,
                        remainingExternalObjectSlots: 0,
                    },
                    finalFormulaShape: "preterit-agentive-nounstem-incorporated-in-vnc-matrix",
                    finalFormulaShapeDoesNotLicenseRole: true,
                    functionUseOwnsObjectSlots: false,
                    sourceRouteFrameRequired: true,
                    andrewsSection: "Andrews 35.12",
                    generationStatus: "diagnostic-only-nawat-evidence-required",
                },
            ],
            participantEmbedRoles: ["incorporated-object", "incorporated-adverb"],
            routeStage: "audit-lesson-35",
            diagnosticId: "preterit-agentive-diagnostic-partial",
        }
    );
    const lesson36Frame = ctx.buildLesson36NominalizedVncPursuitFrame();
    s.eq(
        "Lesson 36 pursuit frame covers every Andrews nominalized-VNC subsection",
        {
            kind: lesson36Frame.kind,
            stepNumber: lesson36Frame.stepNumber,
            aimStatus: lesson36Frame.aimStatus,
            pdfRefs: lesson36Frame.pdfRefs,
            subsectionRefs: lesson36Frame.subsectionInventory.map((entry) => entry.andrewsSection),
            generationAllowed: lesson36Frame.generationAllowed,
            closestPass: lesson36Frame.closestPass,
            hitCount: lesson36Frame.hitCount,
            missCount: lesson36Frame.missCount,
        },
        {
            kind: "lesson-36-nominalized-vnc-pursuit-frame",
            stepNumber: 36,
            aimStatus: "shooting",
            pdfRefs: [
                "Andrews Lesson 36.1",
                "Andrews Lesson 36.2",
                "Andrews Lesson 36.3",
                "Andrews Lesson 36.4",
                "Andrews Lesson 36.5",
                "Andrews Lesson 36.6",
                "Andrews Lesson 36.7",
                "Andrews Lesson 36.8",
                "Andrews Lesson 36.9",
                "Andrews Lesson 36.10",
                "Andrews Lesson 36.11",
                "Andrews Lesson 36.12",
            ],
            subsectionRefs: [
                "36.1",
                "36.2",
                "36.3",
                "36.4",
                "36.5",
                "36.6",
                "36.7",
                "36.8",
                "36.9",
                "36.10",
                "36.11",
                "36.12",
            ],
            generationAllowed: false,
            closestPass: false,
            hitCount: 1,
            missCount: 0,
        }
    );
    s.eq(
        "Lesson 36 frame records nominalized VNC architecture and action contrasts",
        {
            degrees: lesson36Frame.customaryPresentAgentiveFrame.twoDegreesOfNominalization,
            reanalysisNiFinal: lesson36Frame.customaryPresentAgentiveFrame.reanalysisFrame.customaryPresentNiAlwaysFinalConstituent,
            fullNominalEmbed: lesson36Frame.customaryPresentAgentiveFrame.fullyNominalizedFrame.canFillEmbedSubpositionOfCompoundStem,
            patientivePossessiveAllowed: lesson36Frame.customaryPresentPatientiveFrame.possessiveStateAllowed,
            instrumentiveTwoStems: lesson36Frame.instrumentiveFrame.paradigmRequiresTwoDifferentNominalizedStems,
            presentStateRestriction: lesson36Frame.presentAgentiveFrame.stateRestriction,
            futureSingularDyad: lesson36Frame.futureAgentiveFrame.singularSubjectNumberDyad,
            actionTypes: lesson36Frame.actionNncFrame.types,
            passiveActionSource: lesson36Frame.actionNncFrame.passiveActionFrame.sourceVoice,
            activeActionSubjectToPossessor: lesson36Frame.actionNncFrame.activeActionFrame.sourceSubjectTransformsToPossessor,
            contrastKeepsPreteritSubject: lesson36Frame.actionNncFrame.contrastFrame.preteritAgentiveSourceSubjectRemainsNncSubject,
            routeStage: lesson36Frame.frames.routeContract.routeStage,
            diagnosticId: lesson36Frame.contractDiagnostics[0].id,
        },
        {
            degrees: ["reanalysis", "fully nominalized"],
            reanalysisNiFinal: true,
            fullNominalEmbed: true,
            patientivePossessiveAllowed: false,
            instrumentiveTwoStems: true,
            presentStateRestriction: "absolutive-only",
            futureSingularDyad: "qui-0",
            actionTypes: ["passive-action", "active-action"],
            passiveActionSource: "passive",
            activeActionSubjectToPossessor: true,
            contrastKeepsPreteritSubject: true,
            routeStage: "audit-lesson-36",
            diagnosticId: "nominalized-vnc-diagnostic-partial",
        }
    );
    const lesson37Frame = ctx.buildLesson37DeverbalNounstemPursuitFrame();
    s.eq(
        "Lesson 37 pursuit frame covers every Andrews deverbal-nounstem subsection",
        {
            kind: lesson37Frame.kind,
            stepNumber: lesson37Frame.stepNumber,
            aimStatus: lesson37Frame.aimStatus,
            pdfRefs: lesson37Frame.pdfRefs,
            subsectionRefs: lesson37Frame.subsectionInventory.map((entry) => entry.andrewsSection),
            generationAllowed: lesson37Frame.generationAllowed,
            closestPass: lesson37Frame.closestPass,
            hitCount: lesson37Frame.hitCount,
            missCount: lesson37Frame.missCount,
        },
        {
            kind: "lesson-37-deverbal-nounstem-pursuit-frame",
            stepNumber: 37,
            aimStatus: "shooting",
            pdfRefs: [
                "Andrews Lesson 37.1",
                "Andrews Lesson 37.2",
                "Andrews Lesson 37.3",
                "Andrews Lesson 37.4",
                "Andrews Lesson 37.5",
                "Andrews Lesson 37.6",
                "Andrews Lesson 37.7",
                "Andrews Lesson 37.8",
                "Andrews Lesson 37.9",
            ],
            subsectionRefs: [
                "37.1",
                "37.2",
                "37.3",
                "37.4",
                "37.5",
                "37.6",
                "37.7",
                "37.8",
                "37.9",
            ],
            generationAllowed: false,
            closestPass: false,
            hitCount: 1,
            missCount: 0,
        }
    );
    s.eq(
        "Lesson 37 frame records deverbal architecture and patientive source families",
        {
            derivedFromVncCore: lesson37Frame.deverbalOverviewFrame.derivedFromVncCoreNotPredicate,
            zSuffix: lesson37Frame.activeActionZFrame.suffix,
            lizSuffixalUnit: lesson37Frame.activeActionLizFrame.suffixalUnit,
            potentialPatientDropsObject: lesson37Frame.activeActionParticularsFrame.potentialPatientFrame.transitivePotentialPatientLacksObjectPronoun,
            activePossessorAgent: lesson37Frame.activePassiveActionContrastFrame.activeActionPossessorRepresentsAgent,
            multipleNucleusSupplement: lesson37Frame.multipleNucleusFrame.activeActionNncCanServeAsSupplement,
            patientiveFamilies: lesson37Frame.patientiveOverviewFrame.sourceFamilies,
            passiveBlocksIntransitive: lesson37Frame.passivePatientiveFrame.passiveSourceCannotHaveIntransitiveUltimateSource,
            routeStage: lesson37Frame.frames.routeContract.routeStage,
            diagnosticId: lesson37Frame.contractDiagnostics[0].id,
        },
        {
            derivedFromVncCore: true,
            zSuffix: "z",
            lizSuffixalUnit: "liz",
            potentialPatientDropsObject: true,
            activePossessorAgent: true,
            multipleNucleusSupplement: true,
            patientiveFamilies: [
                "passive-core",
                "impersonal-core",
                "perfective-active-core",
                "imperfective-active-core",
                "verb-root-or-stock",
            ],
            passiveBlocksIntransitive: true,
            routeStage: "audit-lesson-37",
            diagnosticId: "deverbal-nounstem-diagnostic-partial",
        }
    );
    const lesson38Frame = ctx.buildLesson38ImpersonalPatientivePursuitFrame();
    s.eq(
        "Lesson 38 pursuit frame covers every Andrews impersonal-patientive subsection",
        {
            kind: lesson38Frame.kind,
            stepNumber: lesson38Frame.stepNumber,
            aimStatus: lesson38Frame.aimStatus,
            pdfRefs: lesson38Frame.pdfRefs,
            subsectionRefs: lesson38Frame.subsectionInventory.map((entry) => entry.andrewsSection),
            generationAllowed: lesson38Frame.generationAllowed,
            closestPass: lesson38Frame.closestPass,
            hitCount: lesson38Frame.hitCount,
            missCount: lesson38Frame.missCount,
        },
        {
            kind: "lesson-38-impersonal-patientive-pursuit-frame",
            stepNumber: 38,
            aimStatus: "shooting",
            pdfRefs: [
                "Andrews Lesson 38.1",
                "Andrews Lesson 38.1.1",
                "Andrews Lesson 38.1.1.a",
                "Andrews Lesson 38.1.1.b",
                "Andrews Lesson 38.1.1.c",
                "Andrews Lesson 38.1.1.d",
                "Andrews Lesson 38.1.2",
                "Andrews Lesson 38.1.3",
                "Andrews Lesson 38.1.3.a",
                "Andrews Lesson 38.1.3.b",
                "Andrews Lesson 38.1.3.c",
                "Andrews Lesson 38.1.4",
                "Andrews Lesson 38.1.4.a",
                "Andrews Lesson 38.1.4.b",
                "Andrews Lesson 38.1.4.c",
                "Andrews Lesson 38.1.5",
                "Andrews Lesson 38.1.6",
                "Andrews Lesson 38.2",
                "Andrews Lesson 38.2.1",
                "Andrews Lesson 38.2.2",
            ],
            subsectionRefs: [
                "38.1",
                "38.1.1",
                "38.1.1.a",
                "38.1.1.b",
                "38.1.1.c",
                "38.1.1.d",
                "38.1.2",
                "38.1.3",
                "38.1.3.a",
                "38.1.3.b",
                "38.1.3.c",
                "38.1.4",
                "38.1.4.a",
                "38.1.4.b",
                "38.1.4.c",
                "38.1.5",
                "38.1.6",
                "38.2",
                "38.2.1",
                "38.2.2",
            ],
            generationAllowed: false,
            closestPass: false,
            hitCount: 1,
            missCount: 0,
        }
    );
    s.eq(
        "Lesson 38 frame records impersonal patientive routing and compound boundaries",
        {
            sourceCore: lesson38Frame.impersonalPatientiveOverviewFrame.sourceCore,
            passiveImpersonalSplit: lesson38Frame.impersonalPatientiveOverviewFrame.passiveAndImpersonalMustNotBeCollapsed,
            rootPlusYaUsesRoot: lesson38Frame.intransitiveSourceFrame.loSourceFrame.rootPlusYaMayUseRootNotStem,
            reflexiveNe: lesson38Frame.reflexiveSourceFrame.reflexiveObjectUsesShuntlineNe,
            nonhumanProjective: lesson38Frame.projectiveNonhumanSourceFrame.directObjectMustBeNonhuman,
            finalAReplaced: lesson38Frame.projectiveNonhumanSourceFrame.huaSourceFrame.finalAReplacedByI,
            humanTeRoute: lesson38Frame.projectiveTeSourceFrame.usesImpersonalTlaPrefix,
            anomalousTeContrast: lesson38Frame.humanNonhumanContrastFrame.teCanNameNonhumanEntityAsAnomalousPattern,
            translationOverlap: lesson38Frame.translationOverlapFrame.sharedTranslationDoesNotMeanSameStructure,
            compoundModes: lesson38Frame.compoundPatientiveFrame.passiveAndImpersonalPatientivesCanBeCompoundInTwoWays,
            routeStage: lesson38Frame.frames.routeContract.routeStage,
            diagnosticId: lesson38Frame.contractDiagnostics[0].id,
        },
        {
            sourceCore: "impersonal VNC core",
            passiveImpersonalSplit: true,
            rootPlusYaUsesRoot: true,
            reflexiveNe: true,
            nonhumanProjective: true,
            finalAReplaced: true,
            humanTeRoute: true,
            anomalousTeContrast: true,
            translationOverlap: true,
            compoundModes: true,
            routeStage: "audit-lesson-38",
            diagnosticId: "impersonal-patientive-diagnostic-partial",
        }
    );
    const lesson39Frame = ctx.buildLesson39PatientiveOperationsPursuitFrame();
    s.eq(
        "Lesson 39 pursuit frame covers every Andrews patientive-operations subsection",
        {
            kind: lesson39Frame.kind,
            stepNumber: lesson39Frame.stepNumber,
            aimStatus: lesson39Frame.aimStatus,
            pdfRefs: lesson39Frame.pdfRefs,
            subsectionRefs: lesson39Frame.subsectionInventory.map((entry) => entry.andrewsSection),
            generationAllowed: lesson39Frame.generationAllowed,
            closestPass: lesson39Frame.closestPass,
            hitCount: lesson39Frame.hitCount,
            missCount: lesson39Frame.missCount,
        },
        {
            kind: "lesson-39-patientive-operations-pursuit-frame",
            stepNumber: 39,
            aimStatus: "shooting",
            pdfRefs: [
                "Andrews Lesson 39.1",
                "Andrews Lesson 39.1.1",
                "Andrews Lesson 39.1.2",
                "Andrews Lesson 39.1.3",
                "Andrews Lesson 39.2",
                "Andrews Lesson 39.2.1",
                "Andrews Lesson 39.2.2",
                "Andrews Lesson 39.3",
                "Andrews Lesson 39.3.1",
                "Andrews Lesson 39.3.2",
                "Andrews Lesson 39.3.3",
                "Andrews Lesson 39.3.4",
                "Andrews Lesson 39.3.5",
                "Andrews Lesson 39.3.6",
                "Andrews Lesson 39.4",
                "Andrews Lesson 39.4.1",
                "Andrews Lesson 39.4.2",
                "Andrews Lesson 39.4.3",
                "Andrews Lesson 39.4.4",
                "Andrews Lesson 39.5",
                "Andrews Lesson 39.6",
                "Andrews Lesson 39.7",
                "Andrews Lesson 39.8",
                "Andrews Lesson 39.9",
            ],
            subsectionRefs: [
                "39.1",
                "39.1.1",
                "39.1.2",
                "39.1.3",
                "39.2",
                "39.2.1",
                "39.2.2",
                "39.3",
                "39.3.1",
                "39.3.2",
                "39.3.3",
                "39.3.4",
                "39.3.5",
                "39.3.6",
                "39.4",
                "39.4.1",
                "39.4.2",
                "39.4.3",
                "39.4.4",
                "39.5",
                "39.6",
                "39.7",
                "39.8",
                "39.9",
            ],
            generationAllowed: false,
            closestPass: false,
            hitCount: 1,
            missCount: 0,
        }
    );
    s.eq(
        "Lesson 39 frame records patientive family operations and valence boundaries",
        {
            perfectiveTli: lesson39Frame.perfectivePatientiveFrame.belongsToTliClass,
            perfectiveEndings: lesson39Frame.perfectivePatientiveFrame.allowedPerfectiveCoreEndingsNawat,
            imperfectiveTi: lesson39Frame.imperfectivePatientiveFrame.belongsToTiClass,
            characteristicMatrix: lesson39Frame.characteristicPropertyFrame.nounstemMatrix,
            organicPossessiveOnly: lesson39Frame.characteristicPropertyFrame.organicPossessionFrame.organicPossessionOnlyPossessiveState,
            rootStockChoices: lesson39Frame.rootStockPatientiveFrame.niDestockalFrame.suffixChoices,
            multipleProcedures: lesson39Frame.multipleDerivationFrame.procedures,
            compoundNominal: lesson39Frame.patientiveCompoundEmbedFrame.patientiveNounstemCanEmbedInNominalCompound,
            complementPossessorToObject: lesson39Frame.incorporatedComplementFrame.possessiveSourceFrame.possessorPronounTransformsToMainlineObjectPronoun,
            objectMatrices: lesson39Frame.incorporatedObjectFrame.matrices,
            complementRoute: {
                kind: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.kind,
                sourcePrincipal: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.sourcePrincipalVnc.formulaType,
                sourceAdjunct: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.sourceAdjunctNnc.formulaType,
                embedRole: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.embedRole,
                consumedObjectSlot: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.consumedObjectSlot,
                remainingExternalObjectSlotIds: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.remainingExternalObjectSlotIds,
                valenceDelta: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.valenceDelta,
                andrewsSection: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.andrewsSection,
                generationStatus: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.generationStatus,
                finalFormulaShapeDoesNotLicenseRole: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.finalFormulaShapeDoesNotLicenseRole,
                functionUseOwnsObjectSlots: lesson39Frame.incorporatedComplementFrame.objectSlotOwnership.functionUseOwnsObjectSlots,
                sourceRouteFrameRequired: lesson39Frame.incorporatedComplementFrame.incorporationRouteFrame.sourceRouteFrameRequired,
            },
            objectRoute: {
                kind: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.kind,
                sourcePrincipal: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.sourcePrincipalVnc.formulaType,
                sourceAdjunct: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.sourceAdjunctNnc.formulaType,
                embedRole: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.embedRole,
                consumedObjectSlot: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.consumedObjectSlot,
                remainingExternalObjectSlotIds: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.remainingExternalObjectSlotIds,
                valenceDelta: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.valenceDelta,
                andrewsSection: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.andrewsSection,
                generationStatus: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.generationStatus,
                finalFormulaShapeDoesNotLicenseObjectSlots: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.finalFormulaShapeDoesNotLicenseObjectSlots,
                functionUseOwnsObjectSlots: lesson39Frame.incorporatedObjectFrame.objectSlotOwnership.functionUseOwnsObjectSlots,
                sourceRouteFrameRequired: lesson39Frame.incorporatedObjectFrame.incorporationRouteFrame.sourceRouteFrameRequired,
            },
            participantRouteRoles: [
                lesson39Frame.frames.participantFrame.incorporatedComplementRouteFrame.embedRole,
                lesson39Frame.frames.participantFrame.incorporatedObjectRouteFrame.embedRole,
            ],
            yoTlOmission: lesson39Frame.characteristicPropertyEmbedFrame.yoTlMatrixCanBeOmittedWithFullDerivedMeaning,
            routeStage: lesson39Frame.frames.routeContract.routeStage,
            diagnosticId: lesson39Frame.contractDiagnostics[0].id,
        },
        {
            perfectiveTli: true,
            perfectiveEndings: ["w", "k", "kw", "s", "sh", "n", "glottal", "l", "tz"],
            imperfectiveTi: true,
            characteristicMatrix: "(-yo)-tl",
            organicPossessiveOnly: true,
            rootStockChoices: ["c", "x", "z", "ch"],
            multipleProcedures: ["passive-core", "impersonal-core", "perfective-active-core", "imperfective-active-core", "root-or-stock"],
            compoundNominal: true,
            complementPossessorToObject: true,
            objectMatrices: ["tla-(tlani)", "tla-(ih-tlani)", "tla-(tem-o-a)"],
            complementRoute: {
                kind: "lesson-39-patientive-incorporation-route-frame",
                sourcePrincipal: "CNV",
                sourceAdjunct: "CNN",
                embedRole: "incorporated-complement",
                consumedObjectSlot: "complement-slot",
                remainingExternalObjectSlotIds: ["mainline-object"],
                valenceDelta: {
                    complementSlots: 1,
                    incorporatedObjectSlots: 0,
                    remainingExternalObjectSlots: 1,
                },
                andrewsSection: "Andrews 39.7",
                generationStatus: "diagnostic-only-nawat-evidence-required",
                finalFormulaShapeDoesNotLicenseRole: true,
                functionUseOwnsObjectSlots: false,
                sourceRouteFrameRequired: true,
            },
            objectRoute: {
                kind: "lesson-39-patientive-incorporation-route-frame",
                sourcePrincipal: "CNV",
                sourceAdjunct: "CNN",
                embedRole: "incorporated-object",
                consumedObjectSlot: "obj1",
                remainingExternalObjectSlotIds: ["applicative-object"],
                valenceDelta: {
                    complementSlots: 0,
                    incorporatedObjectSlots: 1,
                    remainingExternalObjectSlots: 1,
                },
                andrewsSection: "Andrews 39.8",
                generationStatus: "diagnostic-only-nawat-evidence-required",
                finalFormulaShapeDoesNotLicenseObjectSlots: true,
                functionUseOwnsObjectSlots: false,
                sourceRouteFrameRequired: true,
            },
            participantRouteRoles: ["incorporated-complement", "incorporated-object"],
            yoTlOmission: true,
            routeStage: "audit-lesson-39",
            diagnosticId: "patientive-operations-diagnostic-partial",
        }
    );

    return s;
}

module.exports = { run };
