// src/lessons/registry.js
// Curriculum metadata for the 58-lesson book sequence.
// This is NOT the physical architecture of the engine.
// Lessons are pedagogical entry points over the grammar engine.
//
// Status values:
//   "implemented"           — engine fully supports this domain
//   "partially-implemented" — some coverage, incomplete
//   "placeholder"           — no conjugation content or not yet mapped
//   "not-mapped"            — content exists in book but not in engine

const LESSON_REGISTRY = [
    {
        id: 1,
        title: "Linguistic Preliminaries",
        status: "partially-implemented",
        engineDependencies: ["core/concepts"],
        exampleVerbs: [],
        notes: "Diagnostic concept and notation registry exists; full glossary UI is not modeled",
    },
    {
        id: 2,
        title: "Pronunciation. Orthography",
        status: "partially-implemented",
        engineDependencies: ["core/phonology", "core/orthography"],
        exampleVerbs: [],
        notes: "Modern phonology and syllabification support exist; Andrews/Classical orthography is not fully modeled",
    },
    {
        id: 3,
        title: "Particles",
        status: "partially-implemented",
        engineDependencies: ["core/particles"],
        exampleVerbs: [],
        notes: "Diagnostic particle placement metadata exists; no confirmed particle inventory or generation",
    },
    {
        id: 4,
        title: "Nuclear Clauses",
        status: "partially-implemented",
        engineDependencies: ["core/clause"],
        exampleVerbs: [],
        notes: "Nuclear-clause shell metadata exists; full sentence syntax is not modeled",
    },
    {
        id: 5,
        title: "The Intransitive VNC Formula. Subject Pronouns. Tense Morphs",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc", "core/preterit"],
        exampleVerbs: ["nemi", "yawi", "kisa", "miki"],
        notes: "Core intransitive paradigm fully implemented",
    },
    {
        id: 6,
        title: "The Transitive VNC Formula. Object Pronouns",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc"],
        exampleVerbs: ["kua", "itta", "maka"],
        notes: "Transitive paradigm fully implemented",
    },
    {
        id: 7,
        title: "Verbstem Classes",
        status: "implemented",
        engineDependencies: ["core/vnc", "core/preterit"],
        exampleVerbs: ["nemi", "pewa", "maka", "itta"],
        notes: "All preterit classes (A/B/C/D) implemented",
    },
    {
        id: 8,
        title: "Further Remarks on VNCs. Basic Sentences",
        status: "partially-implemented",
        engineDependencies: ["core/vnc", "core/agreement", "core/sentence"],
        exampleVerbs: [],
        notes: "VNC mechanics and diagnostic sentence-layer metadata exist; sentence generation is not modeled",
    },
    {
        id: 9,
        title: "The Optative Mood. Wish Sentences. Command/Exhortation Sentences",
        status: "partially-implemented",
        engineDependencies: ["core/vnc", "core/sentence"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Finite optative VNC forms are implemented; sentence-level optative constructions are not modeled",
    },
    {
        id: 10,
        title: "The Admonitive Mood. Admonition Sentences",
        status: "partially-implemented",
        engineDependencies: ["core/vnc", "core/sentence"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Finite admonitive VNC forms are implemented; sentence-level admonition constructions are not modeled",
    },
    {
        id: 11,
        title: "Irregular VNCs",
        status: "partially-implemented",
        engineDependencies: ["core/irregulars"],
        exampleVerbs: ["kati", "yawi", "witzi", "weya"],
        notes: "Nawat suppletive subset is implemented; Andrews irregular perfectives, defective verbs, and tense-meaning shifts remain incomplete",
    },
    {
        id: 12,
        title: "The Absolutive-State NNC Formula. Subject Pronouns",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Noun derivations exist; full NNC paradigm generation is incomplete",
    },
    {
        id: 13,
        title: "The Possessive-State NNC Formula. Subject and Possessor Pronouns",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/agreement"],
        exampleVerbs: [],
        notes: "Possessive-state NNC partially implemented",
    },
    {
        id: 14,
        title: "Nounstem Classes",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Stem class detection exists; full class-based NNC generation incomplete",
    },
    {
        id: 15,
        title: "Further Remarks on NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped to engine features",
    },
    {
        id: 16,
        title: "Pronominal NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc", "core/agreement"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 17,
        title: "Supplementation (Part One)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 18,
        title: "Supplementation (Part Two)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 19,
        title: "Supplementation (Part Three)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 20,
        title: "The Nonactive Verbstem",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["nemi", "kua", "maka"],
        notes: "Nonactive derivation fully implemented",
    },
    {
        id: 21,
        title: "The Passive-Voice VNC",
        status: "implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: ["kua", "maka"],
        notes: "Passive VNC implemented via nonactive derivation",
    },
    {
        id: 22,
        title: "Impersonal VNCs",
        status: "implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Impersonal VNC implemented",
    },
    {
        id: 23,
        title: "More on Verb Objects",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc"],
        exampleVerbs: [],
        notes: "Object prefix allomorphy and combinations implemented",
    },
    {
        id: 24,
        title: "Causative Verbstems (First Type). Destockal Verbstems",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["nemi", "kisa", "miki"],
        notes: "Type-1 causative and destockal derivation implemented",
    },
    {
        id: 25,
        title: "Causative Verbstems (Second Type)",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["temu", "tema", "nemi"],
        notes: "Type-2 causative (TIA/WIA/LIA) implemented",
    },
    {
        id: 26,
        title: "Applicative Verbstems",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["maka", "itta", "nemi"],
        notes: "Applicative derivation implemented",
    },
    {
        id: 27,
        title: "Frequentative Verbstems",
        status: "partially-implemented",
        engineDependencies: ["core/derivation/frequentative"],
        exampleVerbs: [],
        notes: "Diagnostic frequentative boundary metadata exists; no confirmed frequentative generation",
    },
    {
        id: 28,
        title: "Compound Verbstems: Verbal Embed",
        status: "partially-implemented",
        engineDependencies: ["core/parsing", "core/vnc"],
        exampleVerbs: [],
        notes: "Verbal embed parsing exists; compound VNC generation partially implemented",
    },
    {
        id: 29,
        title: "Purposive VNCs",
        status: "partially-implemented",
        engineDependencies: ["core/vnc/purposive"],
        exampleVerbs: [],
        notes: "Diagnostic purposive/directional boundary metadata exists; no confirmed purposive generation",
    },
    {
        id: 30,
        title: "Compound Verbstems: Nominal Embed",
        status: "partially-implemented",
        engineDependencies: ["core/parsing", "core/vnc"],
        exampleVerbs: [],
        notes: "Nominal embed parsing exists; generation partially implemented",
    },
    {
        id: 31,
        title: "Compound Nounstems",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/compound"],
        exampleVerbs: [],
        notes: "Diagnostic compound-NNC boundary metadata exists; no confirmed compound nounstem generation",
    },
    {
        id: 32,
        title: "Affective NNCs",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/compound"],
        exampleVerbs: [],
        notes: "Diagnostic affective-NNC boundary metadata exists; no confirmed affective generation",
    },
    {
        id: 33,
        title: "Honorific VNCs. Pejorative VNCs",
        status: "partially-implemented",
        engineDependencies: ["core/vnc", "core/vnc/honorific_pejorative"],
        exampleVerbs: [],
        notes: "Diagnostic honorific/pejorative VNC boundary metadata exists; no confirmed generation",
    },
    {
        id: 34,
        title: "Cardinal-Numeral NNCs",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/numerals"],
        exampleVerbs: [],
        notes: "Diagnostic numeral-NNC boundary metadata exists; no confirmed numeral generation",
    },
    {
        id: 35,
        title: "Nominalization of VNCs (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/nominalization", "core/derivation"],
        exampleVerbs: [],
        notes: "Generated nominal surfaces and diagnostic nominalization boundary metadata exist; preterit-agentive general-use, ownerhood, adverbial, incorporated-complement, and ordinary nounstem ownerhood continuations are partial",
    },
    {
        id: 36,
        title: "Nominalization of VNCs (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/nominalization", "core/derivation"],
        exampleVerbs: [],
        notes: "Agentive, patientive, instrumentive, and action-like nominal surfaces are partial with category metadata; first Andrews 36.3 customary-agentive nominal/VNC compound continuations reach #3 salida",
    },
    {
        id: 37,
        title: "Deverbal Nounstems (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/nominalization", "core/derivation"],
        exampleVerbs: [],
        notes: "Current s/lis active-action generation exists; complete z/liz fixture-backed coverage remains incomplete",
    },
    {
        id: 38,
        title: "Deverbal Nounstems (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/nominalization", "core/derivation"],
        exampleVerbs: [],
        notes: "Patientive branch metadata exists; full patientive nounstem taxonomy remains incomplete",
    },
    {
        id: 39,
        title: "Deverbal Nounstems (Part Three)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/nominalization", "core/derivation"],
        exampleVerbs: [],
        notes: "Patientive branch metadata exists; compound/embed/object patientive behavior remains incomplete",
    },
    {
        id: 40,
        title: "Adjectival NNCs (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/adjectival"],
        exampleVerbs: [],
        notes: "Diagnostic adjectival NNC function boundary metadata exists; full adjective-function model remains incomplete",
    },
    {
        id: 41,
        title: "Adjectival NNCs (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/adjectival"],
        exampleVerbs: [],
        notes: "Diagnostic adjectival NNC function boundary metadata exists; full adjective-function model remains incomplete",
    },
    {
        id: 42,
        title: "Adjectival Modification (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/modification"],
        exampleVerbs: [],
        notes: "Diagnostic adjectival-modification boundary metadata exists; no confirmed modification AST",
    },
    {
        id: 43,
        title: "Adjectival Modification (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/modification"],
        exampleVerbs: [],
        notes: "Diagnostic adjectival-modification boundary metadata exists; no confirmed modification AST",
    },
    {
        id: 44,
        title: "Adverbial Nuclear Clauses",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/adverbial"],
        exampleVerbs: [],
        notes: "Diagnostic adverbial nuclear-clause boundary metadata exists; one legacy adverbio surface remains partial",
    },
    {
        id: 45,
        title: "Relational NNCs (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/relational"],
        exampleVerbs: [],
        notes: "Diagnostic relational-NNC boundary metadata exists; no confirmed relational generation",
    },
    {
        id: 46,
        title: "Relational NNCs (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/relational"],
        exampleVerbs: [],
        notes: "Diagnostic relational-NNC boundary metadata exists; no confirmed relational generation",
    },
    {
        id: 47,
        title: "Relational NNCs (Part Three)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/relational"],
        exampleVerbs: [],
        notes: "Diagnostic relational-NNC boundary metadata exists; no confirmed relational generation",
    },
    {
        id: 48,
        title: "Place-Name NNCs. Gentilic NNCs",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/place_gentilic"],
        exampleVerbs: [],
        notes: "Diagnostic place/gentilic NNC boundary metadata exists; no confirmed place/gentilic generation",
    },
    {
        id: 49,
        title: "Adverbial Modification (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/adjunction"],
        exampleVerbs: [],
        notes: "Diagnostic adverbial-adjunction boundary metadata exists; no confirmed clause-adjunction AST",
    },
    {
        id: 50,
        title: "Adverbial Modification (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/adjunction"],
        exampleVerbs: [],
        notes: "Diagnostic adverbial-adjunction boundary metadata exists; no confirmed clause-adjunction AST",
    },
    {
        id: 51,
        title: "Complementation",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/complement"],
        exampleVerbs: [],
        notes: "Diagnostic complement boundary metadata exists; no confirmed complement AST",
    },
    {
        id: 52,
        title: "Conjunction",
        status: "partially-implemented",
        engineDependencies: ["core/clause", "core/clause/conjunction"],
        exampleVerbs: [],
        notes: "Diagnostic conjunction boundary metadata exists; no confirmed conjunction AST",
    },
    {
        id: 53,
        title: "The Notion of Similarity. Comparison",
        status: "partially-implemented",
        engineDependencies: ["core/comparison"],
        exampleVerbs: [],
        notes: "Diagnostic comparison boundary metadata exists; no confirmed comparison AST",
    },
    {
        id: 54,
        title: "Denominal Verbstems (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: [],
        notes: "Denominal matrix input supported; full derivation partially implemented",
    },
    {
        id: 55,
        title: "Denominal Verbstems (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: [],
        notes: "Partial implementation",
    },
    {
        id: 56,
        title: "Personal-Name NNCs",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/nnc/names"],
        exampleVerbs: [],
        notes: "Diagnostic personal-name NNC boundary metadata exists; no confirmed name generation",
    },
    {
        id: 57,
        title: "Miscellany (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/analysis"],
        exampleVerbs: [],
        notes: "Diagnostic analysis/miscellany boundary metadata exists; no confirmed textual-analysis engine",
    },
    {
        id: 58,
        title: "Miscellany (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/analysis"],
        exampleVerbs: [],
        notes: "Diagnostic analysis/miscellany boundary metadata exists; no confirmed textual-analysis engine",
    },
];

// Summary counts
const LESSON_STATUS_COUNTS = LESSON_REGISTRY.reduce((acc, lesson) => {
    acc[lesson.status] = (acc[lesson.status] || 0) + 1;
    return acc;
}, {});
