// src/lessons/registry.js
// Curriculum metadata for the 58-lesson book sequence.
// This is NOT the physical architecture of the engine.
// Lessons are pedagogical entry points over the grammar engine.
//
// Status values:
//   "implemented"           — engine fully supports this domain
//   "partially-implemented" — some coverage, incomplete
//   "placeholder"           — no conjugation content or not yet mapped
//   "not-mapped"            — content exists in book but not in engine

const LESSON_REGISTRY = [
    {
        id: 1,
        title: "Linguistic Preliminaries",
        status: "placeholder",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Introductory linguistics — no conjugation content",
    },
    {
        id: 2,
        title: "Pronunciation. Orthography",
        status: "implemented",
        engineDependencies: ["core/phonology", "core/orthography"],
        exampleVerbs: [],
        notes: "Phonology and syllabification engine fully implemented",
    },
    {
        id: 3,
        title: "Particles",
        status: "placeholder",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Particles not part of the conjugator's scope",
    },
    {
        id: 4,
        title: "Nuclear Clauses",
        status: "placeholder",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Clause-level structure — not yet mapped to engine",
    },
    {
        id: 5,
        title: "The Intransitive VNC Formula. Subject Pronouns. Tense Morphs",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc", "core/preterit"],
        exampleVerbs: ["nemi", "yawi", "kisa", "miki"],
        notes: "Core intransitive paradigm fully implemented",
    },
    {
        id: 6,
        title: "The Transitive VNC Formula. Object Pronouns",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc"],
        exampleVerbs: ["kua", "itta", "maka"],
        notes: "Transitive paradigm fully implemented",
    },
    {
        id: 7,
        title: "Verbstem Classes",
        status: "implemented",
        engineDependencies: ["core/vnc", "core/preterit"],
        exampleVerbs: ["nemi", "pewa", "maka", "itta"],
        notes: "All preterit classes (A/B/C/D) implemented",
    },
    {
        id: 8,
        title: "Further Remarks on VNCs. Basic Sentences",
        status: "partially-implemented",
        engineDependencies: ["core/vnc", "core/agreement"],
        exampleVerbs: [],
        notes: "VNC mechanics implemented; sentence-level context not in scope",
    },
    {
        id: 9,
        title: "The Optative Mood. Wish Sentences. Command/Exhortation Sentences",
        status: "implemented",
        engineDependencies: ["core/vnc"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Optative tense forms implemented",
    },
    {
        id: 10,
        title: "The Admonitive Mood. Admonition Sentences",
        status: "implemented",
        engineDependencies: ["core/vnc"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Admonitive tense forms implemented",
    },
    {
        id: 11,
        title: "Irregular VNCs",
        status: "implemented",
        engineDependencies: ["core/irregulars"],
        exampleVerbs: ["kati", "yawi", "witzi", "weya"],
        notes: "Suppletive stems kati/yawi/witzi/weya all implemented",
    },
    {
        id: 12,
        title: "The Absolutive-State NNC Formula. Subject Pronouns",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Noun derivations exist; full NNC paradigm generation is incomplete",
    },
    {
        id: 13,
        title: "The Possessive-State NNC Formula. Subject and Possessor Pronouns",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/agreement"],
        exampleVerbs: [],
        notes: "Possessive-state NNC partially implemented",
    },
    {
        id: 14,
        title: "Nounstem Classes",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Stem class detection exists; full class-based NNC generation incomplete",
    },
    {
        id: 15,
        title: "Further Remarks on NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped to engine features",
    },
    {
        id: 16,
        title: "Pronominal NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc", "core/agreement"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 17,
        title: "Supplementation (Part One)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 18,
        title: "Supplementation (Part Two)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 19,
        title: "Supplementation (Part Three)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 20,
        title: "The Nonactive Verbstem",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["nemi", "kua", "maka"],
        notes: "Nonactive derivation fully implemented",
    },
    {
        id: 21,
        title: "The Passive-Voice VNC",
        status: "implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: ["kua", "maka"],
        notes: "Passive VNC implemented via nonactive derivation",
    },
    {
        id: 22,
        title: "Impersonal VNCs",
        status: "implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: ["nemi", "kua"],
        notes: "Impersonal VNC implemented",
    },
    {
        id: 23,
        title: "More on Verb Objects",
        status: "implemented",
        engineDependencies: ["core/agreement", "core/vnc"],
        exampleVerbs: [],
        notes: "Object prefix allomorphy and combinations implemented",
    },
    {
        id: 24,
        title: "Causative Verbstems (First Type). Destockal Verbstems",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["nemi", "kisa", "miki"],
        notes: "Type-1 causative and destockal derivation implemented",
    },
    {
        id: 25,
        title: "Causative Verbstems (Second Type)",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["temu", "tema", "nemi"],
        notes: "Type-2 causative (TIA/WIA/LIA) implemented",
    },
    {
        id: 26,
        title: "Applicative Verbstems",
        status: "implemented",
        engineDependencies: ["core/derivation"],
        exampleVerbs: ["maka", "itta", "nemi"],
        notes: "Applicative derivation implemented",
    },
    {
        id: 27,
        title: "Frequentative Verbstems",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Status unknown — not yet confirmed in engine",
    },
    {
        id: 28,
        title: "Compound Verbstems: Verbal Embed",
        status: "partially-implemented",
        engineDependencies: ["core/parsing", "core/vnc"],
        exampleVerbs: [],
        notes: "Verbal embed parsing exists; compound VNC generation partially implemented",
    },
    {
        id: 29,
        title: "Purposive VNCs",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 30,
        title: "Compound Verbstems: Nominal Embed",
        status: "partially-implemented",
        engineDependencies: ["core/parsing", "core/vnc"],
        exampleVerbs: [],
        notes: "Nominal embed parsing exists; generation partially implemented",
    },
    {
        id: 31,
        title: "Compound Nounstems",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Status unknown",
    },
    {
        id: 32,
        title: "Affective NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 33,
        title: "Honorific VNCs. Pejorative VNCs",
        status: "not-mapped",
        engineDependencies: ["core/vnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 34,
        title: "Cardinal-Numeral NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Data may exist in appendix D; engine not mapped",
    },
    {
        id: 35,
        title: "Nominalization of VNCs (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/derivation"],
        exampleVerbs: [],
        notes: "Some nominalization forms implemented",
    },
    {
        id: 36,
        title: "Nominalization of VNCs (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/derivation"],
        exampleVerbs: [],
        notes: "Some nominalization forms implemented",
    },
    {
        id: 37,
        title: "Deverbal Nounstems (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/derivation"],
        exampleVerbs: [],
        notes: "Agentive/patientive/instrumental forms partially implemented",
    },
    {
        id: 38,
        title: "Deverbal Nounstems (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/derivation"],
        exampleVerbs: [],
        notes: "Partial implementation",
    },
    {
        id: 39,
        title: "Deverbal Nounstems (Part Three)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc", "core/derivation"],
        exampleVerbs: [],
        notes: "Partial implementation",
    },
    {
        id: 40,
        title: "Adjectival NNCs (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Adjectival forms partially implemented",
    },
    {
        id: 41,
        title: "Adjectival NNCs (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Partial implementation",
    },
    {
        id: 42,
        title: "Adjectival Modification (Part One)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 43,
        title: "Adjectival Modification (Part Two)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 44,
        title: "Adverbial Nuclear Clauses",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 45,
        title: "Relational NNCs (Part One)",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 46,
        title: "Relational NNCs (Part Two)",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 47,
        title: "Relational NNCs (Part Three)",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 48,
        title: "Place-Name NNCs. Gentilic NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 49,
        title: "Adverbial Modification (Part One)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 50,
        title: "Adverbial Modification (Part Two)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 51,
        title: "Complementation",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 52,
        title: "Conjunction",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 53,
        title: "The Notion of Similarity. Comparison",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 54,
        title: "Denominal Verbstems (Part One)",
        status: "partially-implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: [],
        notes: "Denominal matrix input supported; full derivation partially implemented",
    },
    {
        id: 55,
        title: "Denominal Verbstems (Part Two)",
        status: "partially-implemented",
        engineDependencies: ["core/derivation", "core/vnc"],
        exampleVerbs: [],
        notes: "Partial implementation",
    },
    {
        id: 56,
        title: "Personal-Name NNCs",
        status: "not-mapped",
        engineDependencies: ["core/nnc"],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 57,
        title: "Miscellany (Part One)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
    {
        id: 58,
        title: "Miscellany (Part Two)",
        status: "not-mapped",
        engineDependencies: [],
        exampleVerbs: [],
        notes: "Not yet mapped",
    },
];

// Summary counts
const LESSON_STATUS_COUNTS = LESSON_REGISTRY.reduce((acc, lesson) => {
    acc[lesson.status] = (acc[lesson.status] || 0) + 1;
    return acc;
}, {});
