"use strict";

const CANVAS_DERIVATION_AUTHORITY = require("../src/core/classical/canvas_lessons24_26_derivation_authority.json");
function requireCanvasAuthorityExample(recordId) {
    const record = CANVAS_DERIVATION_AUTHORITY.examples.find((candidate) => candidate.recordId === recordId);
    if (!record) {
        throw new Error(`Missing canonical Canvas authority record ${recordId}`);
    }
    return record;
}
const CANVAS_L25_253_MIQUI = requireCanvasAuthorityExample("canvas-example-l25-253-miqui-mictia");
const CANVAS_L25_256_TEMO = requireCanvasAuthorityExample("canvas-example-l25-256-temo-temohuia");
const CANVAS_L25_258_TEMI = requireCanvasAuthorityExample("canvas-example-l25-258-temi-temitia");

// Evidence-only transcription of displayed source/result relations in
// ANDREWS_TRANSCRIPTION_CANVAS.md, Lessons 24-25. These strings are audit
// expectations. They never authorize, construct, or select a grammar route.
// `negative` records explicitly rejected formations and `ambiguity` records
// separate multiple printed source paths with ` | `. `evidenceStatus`
// distinguishes printed sources from bounded reconstructions; neither it nor
// the printed target can authorize a grammar route.
const rows = [
    // Lesson 24: valence and nonactive comparisons that are explicitly not
    // causative derivations.
    [24, "24.2", "valence", "Valence-neutral", "(pix-ca)", "tla-(pix-ca)"],
    [24, "24.2", "valence", "Valence-neutral", "(tōca)", "tla-(tōca)"],
    [24, "24.2", "valence", "Valence-neutral", "(mayāna)", "tla-(mayāna)"],
    [24, "24.2", "valence", "Valence-neutral", "(teci)", "tla-(teci)"],
    [24, "24.2", "valence", "Valence-neutral", "(ahci)", "tē-(ahci)"],
    [24, "24.2", "valence", "Valence-neutral", "(mati)", "tla-(mati)"],
    [24, "24.2", "valence", "Valence-neutral", "(tēmiqui)", "tla-(tēmiqui)"],
    [24, "24.2", "valence", "Valence-neutral", "(ciya-hui)", "tla-(ciya-hui)"],
    [24, "24.2", "valence", "Valence-neutral", "(pāqui)", "tla-(pāqui)"],
    [24, "24.2", "valence", "Valence-neutral causative meaning", "(huī-tequi)", "tē- ~ tla-(huī-tequi)"],
    [24, "24.2", "valence", "Valence-neutral causative meaning", "(poz-tequi)", "tla-(poz-tequi)"],
    [24, "24.2", "nonactive", "Intransitive nonactive", "tecih", "tecihua"],
    [24, "24.2", "nonactive", "Transitive passive", "quitecih", "texo ~ texohua"],

    // Lesson 24 type-one causative stems.
    [24, "24.3.1.a", "stem", "Final-i replacement", "(mani)", "tla-(man-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement", "(zahui)", "m-o-(zahu-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement", "(cuepi)", "tla-(cuep-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement", "(tzacui)", "tla-(tzacu-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement", "(tomi)", "tla-(tom-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement", "(ix-tlā-hui)", "tla-(ix-tlā-hu-a)"],
    [24, "24.3.1.a", "stem", "Exact consonant alternation", "(huā-qui)", "tla-(huā-tz-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement with semantic shift", "(tēmi)", "tla-(tēm-a)"],
    [24, "24.3.1.a", "stem", "Final-i replacement with reflexive result", "(pōhui)", "m-o-(pōhu-a)"],
    [24, "24.3.1.b", "stem", "Final-i addition", "(ilpi)", "tla-(ilpi-ā)"],
    [24, "24.3.1.b", "stem", "Final-i addition", "(aqui)", "tla-(aqui-ā)"],
    [24, "24.3.1.b", "stem", "Final-i addition", "(pah-ti)", "tē-(pah-ti-ā)"],
    [24, "24.3.2.a", "stem", "Homophonous final-a replacement", "(ē-hua)", "tla-(ē-hu-a)"],
    [24, "24.3.2.b", "stem", "Root-plus-ya replacement", "(coco-ya)", "tē-(coco-ā)"],
    [24, "24.3.2.b", "stem", "Root-plus-ya replacement", "(tlap-ī-hui-ya)", "tla-(tlap-ī-hui-ā)"],
    [24, "24.3.2.b", "stem", "Root-plus-ya retentive exception", "(yōco-ya)", "tla-(yōco-y-a)"],

    // §24.4 explicitly exposes both typed construction steps. The stock is
    // not itself a VNC-ready verbstem, but it is still a generated grammatical
    // result consumed by the second step.
    [24, "24.4", "stock", "Root plus stock formative", "patl + ā", "patl-ā-"],
    [24, "24.4", "stock", "Stock plus stem formative", "patl-ā- + ni", "(patl-ā-ni)"],

    [24, "24.5.7", "stem", "Destockal ni addition", "(chacu-ā-ni)", "tē-(chacu-ā-ni-ā)"],
    [24, "24.5.7", "stem", "Destockal ni addition", "(ōl-ī-ni)", "m-Ø-(ōl-ī-ni-ā)"],
    [24, "24.5.7", "stem", "Destockal ni addition", "(tzoy-ō-ni)", "tla-(tzoy-ō-ni-ā)"],
    [24, "24.5.7", "stem", "Destockal ni replacement", "(tlap-ā-ni)", "tla-(tlap-ā-n-a)"],
    [24, "24.5.7", "stem", "Destockal ni replacement", "(tzay-ā-ni)", "tla-(tzay-ā-n-a)"],
    [24, "24.5.7", "stem", "Destockal ni replacement", "(cot-ō-ni)", "tla-(cot-ō-n-a)"],
    [24, "24.5.7", "stem", "Dictionary causative with Andrews-implied exact source", "(chich-ī-ni)", "tla-(chich-ī-n-a)", "andrews-implied-exact-source"],
    [24, "24.5.7", "stem", "Destockal hui replacement", "(chay-ā-hui)", "tla-(chay-ā-hu-a)"],
    [24, "24.5.7", "stem", "Destockal hui replacement", "(tōy-ā-hui)", "tla-(tōy-ā-hu-a)"],
    [24, "24.5.7", "stem", "Destockal hui addition", "(tlap-ī-hui)", "tla-(tlap-ī-hui-ā)"],
    [24, "24.5.9", "stem", "Fused destockal replacement", "*(mi-ī-ni) > (mī-ni)", "tla-(mī-n-a)"],
    [24, "24.5.9", "stem", "Fused destockal addition", "*(xi-ī-ni) > (xī-ni)", "tla-(xī-ni-ā)"],
    [24, "24.5.9", "stem", "Fused destockal hui addition", "*(ce-ē-hui) > (cē-hui)", "tla-(cē-hui-ā)"],
    [24, "24.5.9", "coalescence", "Obsolete coalesced source", "*(po-ō-ni)", "*(pō-ni)"],
    [24, "24.5.9", "coalescence", "Obsolete coalesced source", "*(to-ō-ni)", "*(tō-ni)"],
    [24, "24.6.2", "coalescence", "Coalesced hua source", "*(ce-ē-hua)", "(cē-hua)"],
    [24, "24.6.2", "coalescence", "Coalesced hua source", "*(e-ē-hua)", "(ē-hua)"],
    [24, "24.6.3", "synonym", "Destockal synonym", "(tep-ē-hua)", "(tep-ē-hui)"],
    [24, "24.6.3", "synonym", "Destockal synonym", "(tōy-ā-hua)", "(tōy-ā-hui)"],
    [24, "24.6.5", "stem", "Destockal hua replacement", "(chip-ā-hua)", "tla-(chip-ā-hu-a)"],
    [24, "24.6.5", "stem", "Destockal hua replacement", "(tōn-ē-hua)", "tē-(tōn-ē-hu-a)"],
    [24, "24.6.5", "stem", "Dictionary causative with Andrews-presupposed source", "(ciy-ā-hua)", "tla-(ciy-ā-hu-a)", "andrews-presupposed-source"],
    [24, "24.6.5", "stem", "Dictionary causative with Andrews-presupposed source", "(top-ē-hua)", "tē-(top-ē-hu-a)", "andrews-presupposed-source"],
    [24, "24.7", "stem", "i-hui to o-ā", "(pol-i-hui)", "tla-(pol-o-ā)"],
    [24, "24.7", "stem", "i-hui to o-ā", "(tlal-i-hui)", "m-o-(tlal-o-ā)"],
    [24, "24.7", "stem", "a-hui to o-ā", "(pix-a-hui)", "tla-(pix-o-ā)"],
    [24, "24.7 note 1", "stem", "o-hui to o-ā", "(tlap-o-hui)", "tla-(tlap-o-ā)"],
    [24, "24.7 note 2", "negative", "No o-ā causative", "(pil-i-hui)", "no o-ā causative"],
    [24, "24.7 note 2", "stem", "Totally irregular o-ā relation", "(pil-ca)", "tla-(pil-o-ā)"],

    // Lesson 24 class/perfective evidence.
    [24, "24.3.1.a", "perfective", "Class B source perfective", "(tomi)", "(ton)"],
    [24, "24.3.1.a", "perfective", "Class B causative perfective", "tla-(tom-a)", "tla-(ton)"],
    [24, "24.3.1.b", "perfective", "Class C causative perfective", "tla-(ilpi-ā)", "tla-(ilpi-h)"],
    [24, "24.3.2.a", "perfective", "Class A source perfective", "(ē-hua)", "(ē-hua)"],
    [24, "24.3.2.a", "perfective", "Class B causative perfective", "tla-(ē-hu-a)", "tla-(ē-uh)"],
    [24, "24.3.2.b", "perfective", "Root-plus-ya source perfective", "(coco-ya)", "(coco-x)"],
    [24, "24.3.2.b", "perfective", "Root-plus-ya source perfective", "(tlap-ī-hui-ya)", "(tlap-ī-hui-x)"],
    [24, "24.3.2.b", "perfective", "Root-plus-ya causative perfective", "tē-(coco-ā)", "tē-(coco-h)"],
    [24, "24.3.2.b", "perfective", "Root-plus-ya causative perfective", "tla-(tlap-ī-hui-ā)", "tla-(tlap-ī-hui-h)"],
    [24, "24.3.2.b", "perfective", "Exceptional source perfective", "(yōco-ya)", "(yōco-x)"],
    [24, "24.3.2.b", "perfective", "Exceptional causative perfective", "tla-(yōco-y-a)", "tla-(yōco-x)"],
    [24, "24.5.6", "perfective", "Destockal source perfective", "(pey-ō-ni)", "(pey-ō-n)"],
    [24, "24.5.6", "perfective", "Destockal source perfective", "(chay-ā-hui)", "(chay-a-uh)"],
    [24, "24.5.8", "perfective", "Destockal causative perfective", "tla-(cot-ō-n-a)", "tla-(cot-ō-n)"],
    [24, "24.5.8", "perfective", "Destockal causative perfective", "tla-(chay-ā-hu-a)", "tla-(chay-ā-uh)"],
    [24, "24.5.8", "perfective", "Destockal causative perfective", "tla-(chip-ī-ni-ā)", "tla-(chip-ī-ni-h)"],
    [24, "24.5.8", "perfective", "Destockal causative perfective", "tla-(tlap-ī-hui-ā)", "tla-(tlap-ī-hui-h)"],
    [24, "24.6.1", "perfective", "Destockal hua source perfective", "(chip-ā-hua)", "(chip-ā-hua)"],
    [24, "24.6.1", "perfective", "Destockal hua source perfective variant", "(pīn-ā-hua)", "(pīn-ā-hua) ~ (pīn-ā-uh)"],
    [24, "24.6.4", "perfective", "Destockal hua source perfective", "(pin-ē-hua)", "(pin-ē-hua)"],
    [24, "24.6.4", "perfective", "Destockal hua source perfective variant", "(tōn-ē-hua)", "(tōn-ē-hua) ~ (tōn-ē-uh)"],
    [24, "24.6.4", "perfective", "Destockal hua source perfective variant", "(ē-hua)", "(ē-hua) ~ (ē-uh)"],
    [24, "24.6.6", "perfective", "Destockal hua causative perfective", "tla-(chip-ā-hu-a)", "tla-(chip-ā-uh)"],
    [24, "24.6.6", "perfective", "Destockal hua causative perfective", "tē-(tōn-ē-hu-a)", "tē-(tōn-ē-uh)"],
    [24, "24.6.6", "perfective", "Destockal hua causative perfective", "m-Ø-(ē-hu-a)", "m-Ø-(ē-uh)"],
    [24, "24.7", "perfective", "i-hui source perfective", "(pol-i-hui)", "(pol-i-uh)"],
    [24, "24.7", "perfective", "a-hui source perfective", "(pix-a-hui)", "(pix-a-uh)"],
    [24, "24.7", "perfective", "o-ā causative perfective", "tla-(pol-o-ā)", "tla-(pol-o-h)"],

    // Lesson 24 VNC transformations.
    [24, "24.8.1", "vnc", "Specific causative object", "tomi", "nictoma"],
    [24, "24.8.2", "vnc", "Reflexive causative object", "nitomi", "ninotoma"],
    [24, "24.8.2", "vnc", "Reflexive translation comparison", "nicocoya", "ninococoa"],
    [24, "24.8.2", "vnc", "Reflexive translation comparison", "nēhua", "ninēhua"],
    [24, "24.8.3", "vnc", "Nonspecific causative object", "tomohua", "nitlatoma"],

    // Lesson 25 stem formation.
    [25, "25.1", "stem", "Suppletive causative", "(ya-uh)", "tē-(huīca)"],
    [25, "25.1", "stem", "Directional suppletive causative", "(huāl-la-uh)", "huāl+tē-(huīca)"],
    [25, "25.2", "stem", "hua to tiā", "(cochi) > (cochī-hua)", "tē-(cochī-tiā)"],
    [25, "25.2", "stem", "hua to tiā", "tla-(ī) > (ī-hua)", "tē+tla-(ī-tiā)"],
    [25, "25.2", "stem", "hua to tiā", "tla-(itqui) > (itqui-hua)", "tē+tla-(itqui-tiā)"],
    [25, "25.2.1", "stem", "Unexpected hua source", "tla-(caqui) > *(caqui-hua)", "tē+tla-(caquī-tiā)"],
    [25, "25.2.1", "stem", "Unexpected hua source", "(chōca) > *(chōquī-hua)", "tē-(chōquī-tiā)"],
    [25, "25.2.2", "stem", "si to xi hidden hua", "(nēci) > *(nēxi-hua)", "tla-(nēxi-tiā)"],
    [25, "25.2.2", "stem", "si to xi hidden hua", "(iuc-ci) > *(iuc-xi-hua)", "tla-(iuc-xi-tiā)"],
    [25, "25.2.2", "vnc", "Supportive-vowel causative display", "(iuc-ci) > *(iuc-xi-hua) > tla-(iuc-xi-tiā)", "tlaucxitia"],
    [25, "25.2.2", "stem", "sa to xi hidden hua", "(ihza) > *(ihxi-hua)", "tē-(ihxi-tiā)"],
    [25, "25.2.3", "stem", "ta to ti hidden hua", "tla-(itt-a) > *(itt-ī-hua)", "tē+tla-(itt-ī-tiā)"],
    [25, "25.2.3", "stem", "ti to chi hidden hua", "tla-(mati) > *(machi-hua)", "tē+tla-(machi-tiā)"],
    [25, "25.2.4", "stem", "Destockal hui to huī-tiā", "(mix-i-hui)", "tē-(mix-i-huī-tiā)"],
    [25, "25.2.4", "stem", "Destockal hui to huī-tiā", "(tlatz-i-hui)", "m-o-(tlatz-i-huī-tiā)"],
    [25, "25.2.4", "stem", "Destockal hui to hui-tiā", "(pol-i-hui)", "m-o-(pol-i-hui-tiā)"],
    [25, "25.2.4", "stem", "Destockal hui to hui-tiā", "(pach-i-hui)", "tē-(pach-i-hui-tiā)"],
    [25, "25.2.4", "stem", "Destockal hui to huī-tiā", "(ihc-i-hui)", "tē- ~ tla-(ihc-i-huī-tiā)"],
    [25, "25.2.4", "stem", "Attested type-one semantic alternative", "(pach-i-hui)", "tē-(pach-o-ā)"],
    [25, "25.2.4", "stem", "Attested type-one semantic alternative", "(pach-i-hui)", "tla-(pach-o-ā)"],
    [25, "25.2.4", "stem", "Attested synonymous type-one alternative", "(pol-i-hui)", "m-o-(pol-o-ā)"],
    [25, "25.2.4", "negative", "Explicitly unattested type-one alternative; does not exist", "(ihc-i-hui)", "*tē- ~ tla-(ihz-o-ā) does not exist"],
    [25, "25.2.4", "stem", "Valence-sensitive hidden hua", "(hue-tz-ca)", "tē-(hue-tz-qui-tia)"],
    [25, "25.2.4", "stem", "Valence-sensitive hidden hua", "tla-(hue-tz-ca)", "tē+tla-(hue-tz-qui-tiā)"],
    [25, "25.3", "stem", "o-hua to tiā", "(chōca) > (chōc-o-hua)", "tē-(chōc-tiā)"],
    [CANVAS_L25_253_MIQUI.lesson, CANVAS_L25_253_MIQUI.section, CANVAS_L25_253_MIQUI.layer, CANVAS_L25_253_MIQUI.name, CANVAS_L25_253_MIQUI.printedSource, CANVAS_L25_253_MIQUI.printedResult],
    [25, "25.3", "stem", "o-hua to tiā", "(quīza) > (quix-o-hua)", "tē-(quīx-tiā)"],
    [25, "25.3", "stem", "o-hua to tiā", "(nēci) > (nēx-o-hua)", "tla-(nēx-tiā)"],
    [25, "25.3", "stem", "ō to tiā", "(cual-ā-ni) > (cual-ā-n-ō)", "tē-(cual-ā-n-tiā)"],
    [25, "25.3", "stem", "ō to tiā", "(mati) > (mach-ō)", "tē-(mach-tiā)"],
    [25, "25.3", "vnc-reading", "Reflexive mach-tiā", "tē-(mach-tiā)", "m-o-(mach-tiā)"],
    [25, "25.3", "stem", "ō to tiā", "tla-(mati) > (mach-ō)", "tē+tla-(mach-tiā)"],
    [25, "25.3", "vnc-reading", "Reflexive mach-tiā with retained object", "tē+tla-(mach-tiā)", "m-o+tla-(mach-tiā)"],
    [25, "25.3", "vnc-reading", "Reflexive-or-reciprocative reading in context", "m-o+tla-(mach-tiā)", "Tictomachtiah in cuīcatl."],
    [25, "25.3", "vnc-reading", "Reflexive-or-reciprocative reading in context", "m-o+tla-(mach-tiā)", "Quimomachtīzqueh in cuīcatl."],
    [25, "25.3", "ambiguity", "Ambiguous sounded causative object; two source paths", "(mati) | tla-(mati)", "Tēchmachtia."],
    [25, "25.3", "supplementation", "Supplement resolves silently present object", "Tēchmachtia. + Nehmatcānēmiliztli.", "Tēchmachtia in nehmatcānēmiliztli."],
    [25, "25.3", "supplementation", "Nonspecific causative with silently present nuclear object", "Tēmachtia. + Nehmatcānēmiliztli.", "Tēmachtia in nehmatcānēmiliztli."],
    [25, "25.3", "supplementation", "Sounded shuntline variant with nonspecific causative", "Tēmachtia. + Teōcuīcatl.", "Quitēmachtiāya in teōcuīcatl."],
    [25, "25.3", "stem", "Unexpected o-hua alternation", "(mahui) > *(mahu-o-hua)", "tē-(mauh-tiā)"],
    [25, "25.3", "stem", "Unexpected o-hua alternation", "tla-(quēmi) > *(quēm-o-hua)", "tē+tla-(quēn-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "tla-(itt-a) > (itt-a-lō)", "tē+tla-(itt-a-l-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "tla-(chīhua) > (chīhua-lō)", "tē+tla-(chīhua-l-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "tla-(quēmi) > (quēmi-lō)", "tē+tla-(quēmi-l-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "(chol-o-ā) > (chol-o-lō)", "tē-(chol-o-l-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "tla-(tlā-ti-ā) > (tlā-ti-lō)", "tē+tla-(tlā-ti-l-tiā)"],
    [25, "25.4", "stem", "lō to l-tiā", "tla-(cuā) > (cua-lō)", "tē+tla-(cua-l-tiā)"],
    [25, "25.4.1", "stem", "Unexpected ka lō", "(chōca) > *(chōca-lō)", "tē-(chōca-l-tiā)"],
    [25, "25.4.1", "stem", "Unexpected ki lō", "(chōca) > *(chōqui-lō)", "tē-(chōqui-l-tiā)"],
    [25, "25.4.1", "stem", "Unexpected ki lō", "tē+tla-(maca) > *(maqui-lō)", "tē+tē+tla-(maqui-l-tiā)"],
    [25, "25.4.1", "stem", "Unexpected ki lō", "tla-(caqui) > *(caqui-lō)", "tē+tla-(caqui-l-tiā)"],
    [25, "25.4.2", "stem", "Unexpected ni lō", "(cual-ā-ni) > *(cual-ā-ni-lō)", "tē-(cual-ā-ni-l-tiā)"],
    [25, "25.4.2", "stem", "Unexpected na lō", "(cual-ā-ni) > *(cual-ā-na-lō)", "tē-(cual-ā-na-l-tiā)"],
    [25, "25.4.3", "stem", "cua to cui lō", "tla-(tzacu-a) > *(tzacu-i-lō)", "tē+tla-(tzacu-i-l-tiā)"],
    [25, "25.4.4", "stem", "si to xi lō", "tē-(imacaci) > *(imacaxi-lō)", "tē+tē-(imacaxi-l-tiā)"],
    [25, "25.4.4", "stem", "sa to xi lō", "(ihza) > *(ihxi-lō)", "tē-(ihxi-l-tiā)"],
    [25, "25.4.5", "stem", "hua lō", "tla-(ix-tlā-hu-a) > *(ix-tlā-hu-a-lō)", "tē+tla-(ix-tlā-hu-a-l-tiā)"],
    [25, "25.4.5", "stem", "hui lō", "tla-(ix-tlā-hu-a) > *(ix-tlā-hu-i-lō)", "tē+tla-(ix-tlā-hu-i-l-tiā)"],
    [25, "25.4.6", "stem", "ti to chi lō", "tla-(mati) > *(machi-lō)", "tē+tla-(machi-l-tiā)"],
    [25, "25.4.7", "stem", "Denominal ti lō", "*(itz-ti) > *(itz-ti-lō)", "tē-(itz-ti-l-tiā)"],
    [25, "25.4.8", "stem", "Root-plus-ya lō", "(tlaōco-ya) > (tlaōco-lō)", "tē-(tlaōco-l-tiā)"],
    [25, "25.4.8", "stem", "Root-plus-ya lō", "(āhui-ya) > (āhui-lō)", "tē-(āhui-l-tiā)"],
    [25, "25.4.8", "stem", "Root-plus-ya lō variant", "(āhui-ya)", "tē-(āhui-ya-l-tiā)"],
    [25, "25.5.1", "stem", "Denominal ti plus liā", "(tlāca-ti)", "tē- ~ tla-(tlāca-ti-liā)"],
    [25, "25.5.1", "stem", "Denominal ti plus liā", "(nel-ti)", "tla-(nel-ti-liā)"],
    [25, "25.5.1", "stem", "Denominal ti plus liā", "(mazā-ti)", "tē-(mazā-ti-liā)"],
    [25, "25.5.2", "stem", "Root-plus-ya to liā", "(ahhuiā-ya)", "tla-(ahhuiā-liā)"],
    [25, "25.5.2", "stem", "Root-plus-ya to liā", "(ce-ce-ya)", "tla-(ce-ce-liā)"],
    [25, "25.5.2", "stem", "Root-plus-ya to liā", "(xoco-ya)", "tla-(xoco-liā)"],
    [25, "25.5.2", "stem", "Root-plus-ya to liā", "(chichi-ya)", "tla-(chichi-liā)"],
    [25, "25.5.2", "stem", "Deverbal ti-ya to liā", "(te-ti-ya)", "tla-(te-ti-liā)"],
    [25, "25.5.2", "stem", "Deverbal hui-ya to liā", "(xo-xō-hui-ya)", "tla-(xo-xō-hui-liā)"],
    [25, "25.6", "stem", "Direct final-ō huiā", CANVAS_L25_256_TEMO.printedSource, CANVAS_L25_256_TEMO.printedResult],
    [25, "25.6", "stem", "Replacive final-ō huiā", "(tlehcō)", "tla-(tlehca-huiā)"],
    [25, "25.6", "stem", "Replacive final-ō huiā", "(panō)", "tē-(pana-huiā)"],
    [25, "25.6", "stem", "Alternative lō route", "(tlehcō) > *(tlehcō-lō)", "tla-(tlehcō-l-tiā)"],
    [25, "25.6", "stem", "Alternative lō route", "(panō) > *(panō-lō)", "tla-(panō-l-tiā)"],
    [25, "25.6", "stem", "Alternative lō route", "(on-o) > *(on-o-lō)", "tē-(on-o-l-tiā)"],

    // §25.8 intentionally repeats the same source with two selectable outputs.
    [25, "25.8", "stem", "Parallel type one", "(huā-qui)", "tla-(huā-tz-a)"],
    [25, "25.8", "stem", "Parallel type two", "(huā-qui)", "tla-(huā-qui-l-tiā)"],
    [25, "25.8", "stem", "Parallel type one", "(tēmi)", "tla-(tēm-a)"],
    [25, "25.8", "stem", "Parallel type two", CANVAS_L25_258_TEMI.printedSource, CANVAS_L25_258_TEMI.printedResult],
    [25, "25.8", "stem", "Parallel type one with applicative meaning", "(pīn-ā-hua)", "tē-(pin-ā-hu-a)"],
    [25, "25.8", "stem", "Parallel type two", "(pīn-ā-hua)", "tē-(pin-ā-uh-tiā)"],

    // Lesson 25 VNC participant transformations.
    [25, "25.10", "vnc", "Single-object specific", "quīza", "ticquixtia"],
    [25, "25.10", "vnc", "Single-object reflexive", "niquīza", "ninoquīxtia"],
    [25, "25.10", "vnc", "Reflexive translation comparison", "nimahui", "ninomauhtia"],
    [25, "25.10", "vnc", "Reflexive translation comparison", "nihza", "ninihxitia"],
    [25, "25.10", "vnc", "Single-object nonspecific", "quīxohua", "titēquīxtia"],
    [25, "25.11.1.a", "vnc", "Double-object shuntline specific", "nicchīhua", "tinēchchīhualtia"],
    [25, "25.11.1.a", "vnc", "Double-object shuntline plural specific", "niquinnōtza", "tinēchinnōtzaltia"],
    [25, "25.11.1.a", "vnc", "Double-object silent shuntline", "quinnōtzah", "tiquinnōtzaltia"],
    [25, "25.11.1.b", "vnc", "Double-object reciprocative shuntline", "motlazohtlah", "tiquinnetlazohtlaltia"],
    [25, "25.11.1.b", "vnc", "Double-object reflexive shuntline", "ninopetlāhua", "tinēchnepetlāhualtia"],
    [25, "25.11.1.b", "vnc", "Coreferential shuntline exception", "nēchitta", "nicnottītia"],
    [25, "25.11.1.b", "vnc", "Coreferential shuntline exception", "mitznequi", "ticmonectia"],
    [25, "25.11.1.b", "vnc", "Displayed coreferential shuntline result with reconstructed typed reflexive source", "moitta", "nicneittītia", "typed-source-reconstruction-from-independent-andrews-evidence"],
    [25, "25.11.1.c", "vnc", "Double-object nonspecific shuntline", "nitlacāhua", "tinēchtlacāhualtia"],
    [25, "25.11.2.a", "vnc", "Mainline reflexive causative", "niccāhua", "nicnocāhualtia"],
    [25, "25.11.2.b", "vnc", "Mainline reflexive plus nonspecific", "titlachīhua", "timotlachīhualtia"],
    [25, "25.11.3.a", "vnc", "Passive source to nonspecific causative", "chīhualo", "tictēchīhualtia"],
    [25, "25.11.3.a", "vnc", "Passive source to nonspecific causative", "ninōtzalo", "annēchtēnōtzaltiah"],
    [25, "25.11.3.b", "vnc", "Impersonal reciprocative source", "netlazohtlalo", "titēnetlazohtlaltia"],
    [25, "25.11.3.b", "vnc", "Passive coreference exception", "nipiyalo", "ninotēpiyaltia"],
    [25, "25.11.3.c", "vnc", "Impersonal nonspecific source", "tlachīhualo", "titētlachīhualtia"],
    [25, "25.12.1", "vnc", "Triple-object specific", "nimitzcaquītia", "nēchcaquitīltia"],
    [25, "25.12.1", "vnc", "Triple-object plural specific", "niquincaquītia", "tinēchincaquitīltia"],
    [25, "25.12.1", "vnc", "Triple-object nonspecific", "nictlacaquītia", "tinēchtlacaquitīltia"],
    [25, "25.12.1", "vnc", "Triple-object human nonspecific", "nictēcaquītia", "tinēchtēcaquitīltia"],
    [25, "25.12.1", "vnc", "Triple-object reciprocative", "quimocaquītiah", "niquinnecaquitīltia"],
    [25, "25.12.1", "vnc", "Triple-object coreference exception", "nēchtlacaquītia", "nicnotlacaquitīltia"],
    [25, "25.12.2", "vnc", "Triple-object mainline reflexive", "nimitzcaquītia", "nimitznocaquitīltia"],
    [25, "25.12.2", "vnc", "Triple-object mainline reflexive", "nictēcaquītia", "nicnotēcaquitīltia"],
    [25, "25.12.2", "vnc", "Triple-object mainline reflexive", "niquintlacaquītia", "niquinnotlacaquitīltia"],
    [25, "25.12.2", "vnc", "Triple-object mainline reflexive", "nitētlacaquītia", "ninotētlacaquitīltia"],
    [25, "25.12.3", "vnc", "Passive source triple-object", "nicaquitīlo", "tinēchtēcaquitīltia"],
    [25, "25.12.3", "vnc", "Passive source triple-object", "nitlacaquitīlo", "tinēchtētlacaquitīltia"],
    [25, "25.12.3", "vnc", "Impersonal source triple-object", "tētlacaquitīlo", "titētētlacaquitīltia"],

    // Lesson 25 ambiguity and later layers.
    [25, "25.13", "ambiguity", "Alternative active/passive sources; two explicit source paths", "nictēcaquitīa | nicaquitīlo", "tinēchtēcaquitīltia"],
    [25, "25.13", "ambiguity", "Alternative active/passive sources", "nitēnōtza | ninōtzalo", "tinēchtēnōtzaltia"],
    [25, "25.13", "ambiguity", "Reciprocative-order contrast", "tiquinnetlazohtlaltiah", "tiquintotlazohtlaltiah"],
    [25, "25.13", "vnc", "Displayed silent-shuntline result with reconstructed typed specific source", "nicnōtza", "tinēchnōtzaltia", "typed-source-reconstruction-from-independent-andrews-evidence"],
    [25, "25.14", "mood", "Assertion to wish", "Nictlachīhualtia.", "Mā nictlachīhualti."],
    [25, "25.14", "mood", "Assertion to command", "Anquitlachīhualtiah.", "Mā xictlachīhualticān."],
    [25, "25.14", "mood", "Assertion to exhortation", "Ticchīhualtiah.", "Mā ticchīhualtīcān."],
    [25, "25.14", "mood", "Assertion to admonition", "Quichōctiah.", "Mā quichōctihtin."],
    [25, "25.15", "voice", "Active to passive", "Tēchtlachīhualtiah.", "Titlachīhualtīloh."],
    [25, "25.15", "voice", "Active to passive", "Tēchchīhualtiah.", "Tichīhualtīloh."],
    [25, "25.15", "voice", "Active to passive", "Timitzinnōtzaltiah.", "Tiquinnōtzaltīlo."],
    [25, "25.15", "voice", "Active to passive", "Nicnocuitīh.", "Necuitīlōc."],
    [25, "25.15", "voice", "Active to impersonal", "Titētlachīhualtiah.", "Tētlachīhualtīlo."],
    [25, "25.16", "supplementation", "Silent direct object supplement", "Quimmāmāltiah. + Cintli.", "In cintli quimmāmāltiah."],
    [25, "25.16", "supplementation", "Silent direct object supplement", "Tēchītizqueh. + Ātōlli.", "Tēchītizqueh in ātōlli."],
    [25, "25.16", "supplementation", "Silent causative object supplement", "Nēchcaquitīltihqueh. + Tinocnīuh.", "Nēchcaquitīltihqueh in tinocnīuh."],
];

const CLASSICAL_NAHUATL_LESSONS24_25_CANVAS_EXAMPLES = Object.freeze(rows.map(([
    lesson,
    section,
    layer,
    name,
    source,
    result,
    evidenceStatus = "andrews-printed-source",
]) => Object.freeze({ lesson, section, layer, name, source, result, evidenceStatus })));

module.exports = { CLASSICAL_NAHUATL_LESSONS24_25_CANVAS_EXAMPLES };
