"use strict";

// Evidence-only catalog transcribed from ANDREWS_TRANSCRIPTION_CANVAS.md §§26.1-26.23.
// These source/result strings are audit expectations and never authorize or construct grammar.
const CLASSICAL_NAHUATL_LESSON26_CANVAS_EXAMPLES = Object.freeze([
        { section: "26.1", layer: "stem", name: "Inherently applicative", source: "tla-(maca)", result: "tē+tla-(maca)", note: "§26.1.1" },
        { section: "26.1", layer: "stem", name: "Irregular a-applicative", source: "*(itzi)", result: "tē- ~ tla-(itt-a)", note: "§26.1.2" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "*(itzi)", result: "*tē- ~ tla-(itzi)", note: "§26.1.2" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(hue-tz-ca)", result: "tē- ~ tla-(hue-tz-ca)", note: "§26.1.3" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(mayāna)", result: "tla-(mayāna)", note: "§26.1.3" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(ā-miqui)", result: "tē- ~ tla-(ā-miqui)", note: "§26.1.3" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(tēmiqui)", result: "tē- ~ tla-(tēmiqui)", note: "§26.1.3" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(teo-hc-i-hui)", result: "tē- ~ tla-(teo-hc-i-hui)", note: "§26.1.3" },
        { section: "26.1", layer: "stem", name: "Valence-neutral mate", source: "(nene-hc-i-hui)", result: "tē- ~ tla-(nene-hc-i-hui)", note: "§26.1.3" },

        { section: "26.2", layer: "stem", name: "Type 1 · replacive iā", source: "(pin-ā-hua)", result: "tē-(pin-ā-hu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · replacive iā", source: "tla-(ix-tlā-hu-a)", result: "tē+tla-(ix-tlā-hu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · replacive iā", source: "tla-(ihtzoma)", result: "m-o+tla- ~ tē+tla-(ihtzom-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · tla-fusion", source: "tla-(chīhua)", result: "tē-(tla-chihu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · replacive iā", source: "tla-(cōhua)", result: "m-o+tla- ~ tē+tla-(cōhu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · consonant alternation", source: "tla-(ixca)", result: "m-o+tla- ~ tē+tla-(ixqu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · consonant alternation", source: "(oh-quetza)", result: "tē-(oh-quech-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · unattested source", source: "*(ēl-ē-hu-a)", result: "tla-(ēl-ē-hu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · unattested source", source: "*(pal-ē-hu-a)", result: "tē-(pal-ē-hu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · final-i replacement", source: "(quiy-a-hui)", result: "tē-(quiy-a-hu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · final-i replacement", source: "tla-(ih-tlani)", result: "tē+tla-(ih-tlan-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · final-i replacement", source: "tla-(cui)", result: "m-o+tla-(cu-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · denominal ti", source: "(cuica-ti)", result: "tē-(cuica-t-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 · denominal ti", source: "(nāhua-ti)", result: "tē-(nāhua-t-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 causative contrast", source: "(yaca)-tl-", result: "tla-(yaca-ti-ā)" },
        { section: "26.2", layer: "stem", name: "Type 1 applicative contrast", source: "(yaca)-tl-", result: "tla-(yaca-t-iā)" },
        { section: "26.2", layer: "stem", name: "Type 1 causative contrast", source: "(ilpi)", result: "tla-(ilpi-ā)" },
        { section: "26.2", layer: "stem", name: "Type 1 applicative", source: "(ilpi)", result: "m-o-(ilp-iā)" },
        { section: "26.2", layer: "stem", name: "Type 2 alternative", source: "(ilpi)", result: "m-o-(ilpi-liā)" },

        { section: "26.3", layer: "stem", name: "Mainline reflexive applicative", source: "nitlaihyāna", result: "ninotlaihyānilia" },
        { section: "26.3", layer: "stem", name: "Shuntline reflexive applicative", source: "ninihyāna", result: "nicneihyānilia" },

        { section: "26.4", layer: "stem", name: "Type 2 · final-i + liā", source: "(nemi)", result: "tla-(nemi-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · final-i + liā", source: "(tlatz-i-hui)", result: "tla-(tlatz-i-hui-liā)" },
        { section: "26.4", layer: "stem", name: "Irregular huiā alternative", source: "(tlatz-i-hui)", result: "tla-(tlatz-i-l-huiā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · final-i + liā", source: "tla-(caqui)", result: "tē+tla-(caqui-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · tla-fusion", source: "tla-(caqui)", result: "tē-(tla-caqui-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · final-i + liā", source: "tla-(itqui)", result: "tē+tla-(itqui-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · final-i + liā", source: "tla-(āyi)", result: "tē+tla-(āyi-lia)" },
        { section: "26.4", layer: "stem", name: "Type 2 · tla-fusion", source: "tla-(āyi)", result: "tē-(tla-āyi-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · vowel-length alternative", source: "tla-(cui)", result: "tē+tla-(cui-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · si → xi", source: "tla-(pā-hua-ci)", result: "tē+tla-(pā-hua-xi-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · si → xi", source: "tla-(ahci)", result: "tē+tla-(ahxi-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · tzi → chi", source: "(huetzi)", result: "m-o-(huechi-liā)" },
        { section: "26.4", layer: "stem", name: "Type 2 · ti → chi", source: "tla-(mati)", result: "tē+tla-(machi-liā)" },

        { section: "26.5", layer: "stem", name: "Printed analysis convention", source: "tē+tla-(tlā-ti-⎕-liā)", result: "tē+tla-(tlā-ti-liā)" },

        { section: "26.6", layer: "stem", name: "Type 2 · final-iā replacement", source: "tla-(tlami-ā)", result: "tē+tla-(tlami-liā)" },
        { section: "26.6", layer: "stem", name: "Type 2 · reflexive to shuntline", source: "m-o-(tlā-ti-ā)", result: "tē+ne-(tlā-ti-liā)" },
        { section: "26.6", layer: "stem", name: "Causative → applicative", source: "tē+tla-(pāca-l-tiā)", result: "tē+tē+tla-(pāca-l-ti-liā)" },
        { section: "26.6", layer: "stem", name: "Type 1 → Type 2 applicative", source: "tla-(tzitz-qu-iā)", result: "tē+tla-(tzitz-qu-i-liā)" },
        { section: "26.6", layer: "stem", name: "Type 1 → Type 2 applicative", source: "tē+tla-(ix-tlā-hu-iā)", result: "tē+tla+tla-(ix-tlā-hu-i-liā)" },
        { section: "26.6", layer: "stem", name: "Type 2 → Type 2 applicative", source: "tla-(ce-liā)", result: "tē+tla-(ce-li-liā)" },
        { section: "26.6", layer: "stem", name: "Recursive Type 2 applicative", source: "tē+tla-(ce-li-liā)", result: "tē+tē+tla-(ce-li-li-liā)" },

        { section: "26.7", layer: "stem", name: "Type 2 · a → i + liā", source: "tla-(āna)", result: "tē+tla-(āni-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · a → i + liā", source: "tla-(ināya)", result: "tē+tla-(ināyi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · a → i + liā", source: "tla-(ōya)", result: "tē+tla-(ōyi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · ca → qui + liā", source: "(hue-tz-ca)", result: "tē-(hue-tz-qui-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · ca → qui + liā", source: "tla-(pā-tz-ca)", result: "tē+tla-(pa-tz-qui-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · unattested source", source: "*(nān-ca)", result: "tē-(nān-qui-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · sa → xi-liā", source: "tla-(tlāza)", result: "tē+tla-(tlāxi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · tla → chi-liā", source: "tē- ~ tla-(mōtla)", result: "tē+tē- ~ tē+tla-(mōchi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · tza → chi-liā", source: "tē-(nōtza)", result: "tē+tē-(nōchi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · tza → chi-liā", source: "tla-(il-pītza)", result: "tē+tla-(il-pichi-liā)" },
        { section: "26.7", layer: "stem", name: "Type 2 · tla-fusion", source: "tla-(quetza)", result: "tē-(tla-quechi-liā)" },
        { section: "26.7", layer: "stem", name: "Occasional tla → ti-liā", source: "tē-(tla-zo-h-tla)", result: "tē+tē-(tla-zo-h-ti-liā)" },
        { section: "26.7", layer: "stem", name: "Occasional tla → ti-liā", source: "tla-(pa-tla)", result: "tē+tla-(pa-ti-liā)" },
        { section: "26.7", layer: "stem", name: "Applicative ambiguity", source: "tē-(tla-zo-h-tla)", result: "#ni-Ø+c-Ø+⎕-Ø(tla-zo-h-ti-liā)Ø+Ø-Ø#" },
        { section: "26.7", layer: "stem", name: "Causative ambiguity", source: "(tla-zo-h-ti)", result: "#ni-Ø+c-Ø(tla-zo-h-ti-liā)Ø+Ø-Ø#" },

        { section: "26.8", layer: "stem", name: "Class D · preserve long vowel", source: "tla-(pā)", result: "tē+tla-(pā-liā)" },
        { section: "26.8", layer: "stem", name: "Class D · preserve long vowel", source: "tla-(māmā)", result: "tē+tla-(māmā-liā)" },
        { section: "26.8", layer: "stem", name: "Class B iya · append liā", source: "tla-(piya)", result: "tē+tla-(piya-liā)" },
        { section: "26.8", layer: "stem", name: "Class B iya · tla-fusion", source: "(tla-chiya)", result: "tē-(tla-chiya-liā)" },
        { section: "26.8", layer: "stem", name: "Class B eya · delete ya", source: "(ce-ya)", result: "tla-(ce-liā)" },
        { section: "26.8", layer: "stem", name: "Root + oya · delete ya", source: "(tlaōco-ya)", result: "tē-(tlaōco-liā)" },
        { section: "26.8", layer: "stem", name: "Root + oya · delete ya", source: "(coco-ya)", result: "tē-(coco-liā)" },
        { section: "26.8", layer: "stem", name: "Valence-neutral oya · delete ya", source: "tla-(yōco-ya)", result: "tē+tla-(yōco-liā)" },
        { section: "26.8", layer: "stem", name: "Other oya · append liā", source: "tla-(nāmoyā)", result: "tē+tla-(nāmoyā-liā)" },

        { section: "26.9", layer: "stem", name: "o-ā root in l → huiā", source: "tla-(nāpal-o-ā)", result: "tē+tla-(nāpal-huiā)" },
        { section: "26.9", layer: "stem", name: "o-ā root in l → huiā", source: "tla-(pol-o-ā)", result: "tē+tla-(pol-huiā)" },
        { section: "26.9", layer: "stem", name: "o-ā root in l → huiā", source: "tla-(xel-o-ā)", result: "tē+tla-(xel-huiā)" },
        { section: "26.9", layer: "stem", name: "o-ā root in l → huiā", source: "tla-(ihcuil-o-ā)", result: "tē+tla-(ihcuil-huiā)" },
        { section: "26.9", layer: "stem", name: "No intransitive destockal source", source: "tla-(pil-o-ā)", result: "tē+tla-(pil-huiā)" },
        { section: "26.9", layer: "stem", name: "Unattested suppletive source", source: "*tla-(il-o-ā)", result: "tē+tla-(il-huiā)" },
        { section: "26.9", layer: "stem", name: "Suppletive applicative", source: "tla-(iht-o-ā)", result: "tē+tla-(il-huiā)" },
        { section: "26.9", layer: "stem", name: "Intransitive denominal o-ā", source: "(chol-o-ā)", result: "tla-(chol-huiā)" },
        { section: "26.9", layer: "stem", name: "o-ā + a-l-huiā", source: "tla-(iht-o-ā)", result: "tē+tla-(iht-a-l-huiā)" },
        { section: "26.9", layer: "stem", name: "o-ā + i-l-huiā", source: "tla-(pach-o-ā)", result: "tē+tla-(pach-i-l-huiā)" },
        { section: "26.9", layer: "stem", name: "Analogical denominal o-ā", source: "(āyacach-o-ā)", result: "tē-(āyacach-i-l-huiā)" },
        { section: "26.9", layer: "stem", name: "Root in o + l-huiā", source: "tla-(tlap-o-ā)", result: "tē+tla-(tlap-o-l-huiā)" },
        { section: "26.9", layer: "stem", name: "Root in o + l-huiā", source: "(zaca-mo-ā)", result: "tē-(zaca-mo-l-huiā)" },
        { section: "26.9", layer: "stem", name: "Root + ya causative → l-huiā", source: "tla-(coco-a)", result: "tē+tla-(coco-l-huiā)" },
        { section: "26.9", layer: "stem", name: "Exceptional o-ā → liā", source: "tla-(tēm-o-ā)", result: "tē+tla-(tēm-o-liā)" },

        { section: "26.10", layer: "stem", name: "Final-ō + huiā · ambiguous", source: "(temō)", result: "tla-(temō-huiā)" },
        { section: "26.10", layer: "stem", name: "Final-ō + huiā · replacive", source: "(tlehcō)", result: "tla-(tlehca-huia)" },
        { section: "26.10", layer: "stem", name: "Final-ō + huiā · replacive", source: "(panō)", result: "tla-(pana-huiā)" },

        { section: "26.11", layer: "stem", name: "Exceptional tiā · nonactive bridge", source: "tla-(namaca)", result: "*(namaquī-lo)" },
        { section: "26.11", layer: "stem", name: "Exceptional tiā applicative", source: "*(namaquī-lo)", result: "tē+tla-(namaqui-l-tiā)" },
        { section: "26.11", layer: "stem", name: "Exceptional tiā · nonactive bridge", source: "tla-(nequi)", result: "(nec-ō)" },
        { section: "26.11", layer: "stem", name: "Exceptional tiā applicative", source: "(nec-ō)", result: "m-o+tla-(nec-tiā)" },

        { section: "26.12", layer: "stem", name: "Parallel Type 1", source: "tla-(cōhua)", result: "tē+tla-(cōhu-iā)" },
        { section: "26.12", layer: "stem", name: "Parallel Type 2", source: "tla-(cōhua)", result: "tē+tla-(cōhui-liā)" },
        { section: "26.12", layer: "stem", name: "Parallel Type 1 · tla-fusion", source: "tla-(chīhua)", result: "tē-(tla-chīhu-iā)" },
        { section: "26.12", layer: "stem", name: "Parallel Type 2", source: "tla-(chīhua)", result: "tē+tla-(chihui-liā)" },

        { section: "26.15", layer: "transform", name: "Single-object · human", source: "nitlāocoya", result: "nitētlaōcolia" },
        { section: "26.15", layer: "transform", name: "Single-object · specific", source: "nitlāocoya", result: "nimitztlaōcolia" },
        { section: "26.15", layer: "transform", name: "Single-object · reflexive", source: "nitlāocoya", result: "ninotlaōcolia" },
        { section: "26.15", layer: "transform", name: "Tla-fused source", source: "ōnitlahtoh", result: "ōnimitztlahtalhuih" },
        { section: "26.15", layer: "transform", name: "Tla-fused compound source", source: "centlahtohqueh", result: "tēcentlahtalhuihqueh" },

        { section: "26.16", layer: "transform", name: "Double-object · human", source: "nitlapāca", result: "nitētlapāquilia" },
        { section: "26.16", layer: "transform", name: "Double-object · specific", source: "nitlapāca", result: "nictlapāquilia" },
        { section: "26.16", layer: "transform", name: "Double-object · reflexive", source: "nitlapāca", result: "ninotlapāquilia" },
        { section: "26.16", layer: "transform", name: "Double-object · human", source: "nicpāca", result: "nictēpāquilia" },
        { section: "26.16", layer: "transform", name: "Double-object · reflexive", source: "nicpāca", result: "nicnopāquilia" },
        { section: "26.16", layer: "transform", name: "Partly silent shuntline object", source: "quinnāmoya", result: "mitzinnāmoyālia" },
        { section: "26.16", layer: "transform", name: "Shuntline reflexive ne", source: "ninotlātia", result: "nimitznetlātilia" },
        { section: "26.16", layer: "transform", name: "Exceptional reflexive reading", source: "ninonēxtia", result: "ninotēnēxtilia" },
        { section: "26.16", layer: "transform", name: "Expected reflexive applicative", source: "nitēnēxtia", result: "ninotēnēxtilia" },
        { section: "26.16", layer: "transform", name: "Silent source object", source: "nicxeloa", result: "nimitzxelhuia" },
        { section: "26.16", layer: "transform", name: "Silent imported object", source: "niquinnāmoya", result: "niquinnāmoyālia" },
        { section: "26.16", layer: "transform", name: "Supplemented silent object", source: "Ōnechcuilih. + Nāmox.", result: "Ōnechcuilih nāmox." },

        { section: "26.17", layer: "transform", name: "Triple-object · human", source: "tētlapācaltia", result: "tētētlapācaltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · first person", source: "tētlapācaltia", result: "nēchtētlapācaltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · reflexive", source: "tētlapācaltia", result: "motētlapacāltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · human", source: "nimitztlapācaltia", result: "nimitztētlapācaltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · reflexive", source: "nimitztlapācaltia", result: "nimitznotlapacāltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · human", source: "nictēpācaltia", result: "nictētēpācaltilia" },
        { section: "26.17", layer: "transform", name: "Triple-object · reflexive", source: "nictēpācaltia", result: "nicnotēpācaltilia" },
        { section: "26.17", layer: "transform", name: "Two overt objects", source: "mitztlapācaltia", result: "nēchtlapācaltilia" },
        { section: "26.17", layer: "transform", name: "Two overt objects", source: "quitēpācaltia", result: "nēchtēpacāltilia" },
        { section: "26.17", layer: "transform", name: "Two overt objects · human", source: "mitzpācaltia", result: "mitztēpācaltilia" },
        { section: "26.17", layer: "transform", name: "Two overt objects · reflexive", source: "mitzpācaltia", result: "mitzmopacāltilia" },
        { section: "26.17", layer: "transform", name: "One overt object", source: "mitzpācaltia", result: "nēchpacāltilia" },

        { section: "26.18", layer: "transform", name: "Ambiguous result · source A", source: "titētlapācaltia", result: "tinēchtētlapācaltilia" },
        { section: "26.18", layer: "transform", name: "Ambiguous result · source B", source: "tinēchtlapācaltia", result: "tinēchtētlapācaltilia" },
        { section: "26.18", layer: "transform", name: "Ambiguous result · source A", source: "quitēpācaltia", result: "nēchtēpacāltilia" },
        { section: "26.18", layer: "transform", name: "Ambiguous result · source B", source: "nēchpacāltia", result: "nēchtēpacāltilia" },

        { section: "26.19", layer: "later", name: "Assertion → wish", source: "Nēchcōhuilia.", result: "Mā nēchcōhuili." },
        { section: "26.19", layer: "later", name: "Assertion → wish", source: "Noconnotlaxīlia.", result: "Mā cuēl yeh noconnotlaxīli." },
        { section: "26.19", layer: "later", name: "Assertion → command", source: "Ahtictlamilia.", result: "Mā caxictlamili." },
        { section: "26.19", layer: "later", name: "Assertion → exhortation", source: "Tiquinchīhuiliah.", result: "Mā tiquinchihuilicān." },
        { section: "26.19", layer: "later", name: "Assertion → admonition", source: "Antēchihtlacalhuiah.", result: "Mā nēn antēchihtlacalhuihtin." },

        { section: "26.20", layer: "later", name: "Active → passive", source: "Tēchquiyahuiz.", result: "Tiquiyahuilōzqueh." },
        { section: "26.20", layer: "later", name: "Active → passive", source: "Nēchtlacuiliah.", result: "Nitlacuilīlo." },
        { section: "26.20", layer: "later", name: "Active → passive", source: "Mitzcuilihqueh.", result: "Ticuīlilōc." },
        { section: "26.20", layer: "later", name: "Active → passive", source: "Quimilhuiquixtiliāyah.", result: "Ilhuiquixtilīlōyah." },
        { section: "26.20", layer: "later", name: "Active → impersonal", source: "Tētlaxelhuiāyah.", result: "Tētlaxelhuīlōya." },
        { section: "26.20", layer: "later", name: "Active → passive", source: "niquilhuiquīxtilia", result: "ilhuiquixtililo" },

        { section: "26.21", layer: "later", name: "Human ↔ nonhuman direct object", source: "quitlāzah · human", result: "quitlāzah · nonhuman" },
        { section: "26.21", layer: "later", name: "Human ↔ nonhuman direct object", source: "nitēnāmoya", result: "nitlanāmoya" },
        { section: "26.21", layer: "later", name: "Human ↔ nonhuman applicative object", source: "nitēnāhuatia", result: "nitlanāhuatia" },
        { section: "26.21", layer: "later", name: "Human ↔ nonhuman applicative object", source: "nitēnānquilia", result: "nitlanānquilia" },
        { section: "26.21", layer: "later", name: "Direct → applicative reading", source: "tla-(tlāni)", result: "tē-(tlāni)" },
        { section: "26.21", layer: "later", name: "Direct → applicative reading", source: "tla-(nō-nōtza)", result: "tē-(nō-nōtza)" },

        { section: "26.22", layer: "later", name: "Deceptive VNC · source A", source: "tla-(chīhua)", result: "nēchtlachīhuilih" },
        { section: "26.22", layer: "later", name: "Deceptive VNC · source B", source: "tē-(tla-chihu-iā)", result: "nēchtlachīhuilih" },

        { section: "26.23", layer: "later", name: "Object + suffix unit", source: "tla-(cōhua)", result: "nimitztlacōhuilia" },
        { section: "26.23", layer: "later", name: "Causative / applicative ambiguity", source: "(nequi)", result: "tē+tla-(nec-tiā)" },
        { section: "26.23", layer: "later", name: "Causative / applicative ambiguity", source: "(nequi)", result: "tē+tla-(nequi-l-tiā)" },
        { section: "26.23", layer: "later", name: "Causative / applicative ambiguity", source: "(temō)", result: "tla-(temo-huiā)" },
        { section: "26.23", layer: "later", name: "Causative form · applicative meaning", source: "tla-(namaca)", result: "tē+tla-(namaqui-l-tiā)" },
        { section: "26.23", layer: "later", name: "Causative form · applicative meaning", source: "(tla-hua-hua-l-o-ā)", result: "tē- ~ tla-(hua-hua-l-o-ā)" },
        { section: "26.23", layer: "later", name: "False applicative impression", source: "causative analysis", result: "tē-(iht-o-ā)" },
        { section: "26.23", layer: "later", name: "False applicative impression", source: "causative analysis", result: "tē-(ihcuil-o-ā)" }
].map(example => Object.freeze({ ...example })));

module.exports = { CLASSICAL_NAHUATL_LESSON26_CANVAS_EXAMPLES };

